### ISSUE TITLE
Sounds randomly stop working

### ISSUE THREAD

**Issue by lucasgautheron** [assaultcube/AC#1]
It appears that sounds sometimes stop working completely for no apparent reason on windows.
Most often, reloading the map (connecting to a server again) solves the issue temporarily (until it happens again).

Reducing sound details as well as max sounds played at once seem to solve the issue;
There were also reports that switching to an up to date version of openAl soft solves the issue (partially ?)

More details here : http://forum.cubers.net/thread-7201.html

**Comment by aurhat** [comment]
Fixed in commit: https://github.com/assaultcube/AC/commit/c9db8143f478abbec0fc7d4c02b563a68a0967ae
