### ISSUE TITLE
Fly Speed should not be affected by Game Speed

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#102]
When reducing or increasing `/gamespeed` value, ghost speed is changing accordingly.  I think ghost speed should always be fixed at default (100).

This is useful for watching demos.

**Comment by ac-stef** [comment]
Gamespeed is named properly as it sets the speed for the whole game. If you want ghost speed to be always the same, you can counter with "flyspeed" (within certain limits). You can automate this:
alias setgamespeed [ gamespeed $arg1 ; flyspeed (divf 100 $arg1) ]

**Comment by GreenLunar** [comment]
I will rename  tittle, since Fly Speed is changeable.
