### ISSUE TITLE
Allow incorporation of bots in multiplayer game

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#112]
Incorporate bots in multiplayer mode for two reasons:
 * For scenarios when there are not enough players.
 * To have more users to get familiar with the bots of AssaultCube, and they might send feedbacks in concern to improving the bots.

**Comment by aurhat** [comment]
Bots in multiplayer would destroy AC, so no way (you can only use to that custom servers, but they can't be registered in official masterserver).

**Comment by GreenLunar** [comment]
Perhaps it may be allowed by players votes which would always be required on every new game.

**Comment by GreenLunar** [comment]
Reference #54
