### ISSUE TITLE
Adding a new language

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#116]
I want to add Hebrew translation, but when testing my translation, translated parts are empty.

**Comment by aurhat** [comment]
Here you have default font in AC: https://github.com/assaultcube/AC/blob/next/packages/misc/chars_default.png - no Hebrew characters. And new version won't support internationalization.

**Comment by GreenLunar** [comment]
> And new version won't support internationalization.

Why not?

**Comment by aurhat** [comment]
http://forum.cubers.net/thread-7710.html?highlight=ghettos

**Comment by GreenLunar** [comment]
At least create a [assaultcube.desktop](http://slackbuilds.org/slackbuilds/14.1/games/assaultcube/assaultcube.desktop) and add translations of "comment" to it.
