### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#123]
I would like to suggest AssaultCube to offer sponsored maps.

For instance, there is a map called ac_bank which, aside from needing some improvements, is a good map for banks to sponsor AssaultCube.

When a contract ends, Akimbo map packages replaces map models and textures respectively.
Furthermore, you can sponsor several banks at the same time by uploading map models and textures by GeoIP, German players would receive graphics of some German Bank and Russian players would receive graphics of some Russian Bank.

If issue #119 is implemented, it would be possible to extend the maps, not just official maps, which have a proper makeup for sponsoring.

---

Of course, this contrasts a non-conforming graphics of AC that I like **"Revolutions Will Not Be Televised"**.

I know advertisements and propaganda are evil.

**Comment by ac-stef** [comment]
I'd like to refer you to the AC licensing info: http://assault.cubers.net/docs/license.html#entirepackage
"You MAY NOT use AssaultCube for ANY commercial purposes."

**Comment by GreenLunar** [comment]
I do not see a problem.

Assume you have a dedicated blank space for a sign, you may put on that space a texture (advertisement) with a logo of the sponsoring organization and replace it every time a sponsor is changed.

There is no problem.  Think about recruiting sponsors.

**Comment by GreenLunar** [comment]
It is about contents on official package servers, not the software itself.

**Comment by ac-stef** [comment]
You do realise, that it was us who decided, that AC should not be used commercially? Why would we try to go around a rule that actually reflects our wishes?

Also, that "AC package license" is also the only license for lots of contributed media files (it's the default license) - so you have to assume, that at least some contributors intentionally gave their media files to a pure non-commercial project. You should try to respect those wishes.

**Comment by GreenLunar** [comment]
You can license sponsored graphics under the same terms, if you wish.

In the scenario I depicted, *you are paid for **hosting** certain graphics on an official package server*, the graphics license may remain the same.

**Comment by ac-stef** [comment]
Please re-read my last comment.

**Comment by GreenLunar** [comment]
Anyone may use AssaultCube, the software, and its contents freely.

Sponsors pay the official package servers for hosting certain contents, which they wish to be hosted, and these contents may well be free, too.

**Comment by GreenLunar** [comment]
Hello,

I am the Archduke Wolfgang Vlad Fernando the 5th.

I an willing to pay to the official package servers for hosting some scenically [Kopimi](http://kopimi.com/) graphics and [good music](https://musopen.org/).

Sincerely yours,
Wolfgang Vlad Fernando the 5th

**Comment by GreenLunar** [comment]
Please respond to the writings of Archduke Wolfgang Ludwig Vlad Sebastian the 5th.
