### ISSUE TITLE
Remove cigarettes map models

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#124]
From: http://assault.cubers.net/

> Taking place in realistic environments*, with fast, arcade gameplay, it's addictive and fun!
> 
> *Example: Abandoned mine shafts (not alien space ships!)

There is NO good reason to put cigarettes in official maps and package servers of AssaultCube.  Some might start consume that destructive product because of it featured in AssaultCube.

I also suggest not to keep cigarette map models even if a cigarette company pays you to keep it.

**Comment by AC-MPx** [comment]
radical

**Comment by GreenLunar** [comment]
But is true!

**Comment by GreenLunar** [comment]
By including it you are strengthening such bad reality.

Below is a realization.

In Israel, there is a think called "nargilla" (smoking bottle).  There are motion pictured advertisements on televisions in various of clinics of the very few Health maintenance organizations of Israel that "warns" teenagers not to use "nargillas".

When most teenagers are being asked, "Why did you start to use a nargilla?", they would likely tell you that they were exposed to it by the advertisements of The Israel Cancer Association in the near clinic.

The goal of the most of the disease awareness organizations the world over is really to generate more sick people, not otherwise.

NO PRESS IS BAD PRESS!

Keep that in mind.

Remove cigarettes.

**Comment by ac-stef** [comment]
In a game, where the main goal is, to shoot pixel bullets from pixel guns at pixel people to reduce their pixel health, you're concerned about the pixel cigarette butts?

**Comment by GreenLunar** [comment]
I do not know what is pixel health nor pixel cigarette butts.

I am concerned about marketing a bad product, which is cigarettes.

**Comment by GreenLunar** [comment]
>  **Denying** the reality and existence of cigarettes seems a bit off to me, btw.

Then make animated map models of human traffickers of Tel Aviv and put religious incitement campaign graphics, too.

And remove the graphics "Revolutions Will Not Be Televised" which mainstream television is denying, actually.

**Comment by michaelpittino** [comment]
Haha, lmao, please don't let him troll you

**Comment by GreenLunar** [comment]
@michaelpittino If you have nothing productive to post, please do not  post.

Remove cigarettes map models. Do not market bad products.

**Comment by GreenLunar** [comment]
By law of some nation states, new films have no smoking characters.

I do not want my teenage children to see cigarettes while playing AssaultCube and think cigarettes are legitimate.

**Comment by GreenLunar** [comment]
@ac-stef Why dd you close this ticket?

**Comment by GreenLunar** [comment]
There are other objects to simulate real world with.  You do not have to use cigarettes to do so.

Please reopen this ticket.

**Comment by GreenLunar** [comment]
@michaelpittino, Good comment (not really)

Go and tell to your children about it, and enjoy them having cancer for no good reason.

**Comment by GreenLunar** [comment]
Hollywood no longer has cigarettes in movies, but does have success in action films, even without cigarettes.

**Comment by GreenLunar** [comment]
@michaelpittino, in 20 to 30 years from now, please post back, at this thread, if your children would get a cancer caused by cigarettes, though I do hope all of your children would have a healthy life.

**Comment by GreenLunar** [comment]
This is the aforementioned advertisement, to fight (for) using hookahs: http://flix.tapuz.co.il/v/watch-1601956-%D7%A0%D7%A8%D7%92%D7%99%D7%9C%D7%94.html

> Banana, Apple, Cherry, Strawberry.
> 
> In which taste do you like your cancer?
> 
> Nargilla kills like cigarette.

That advertisement gives to irresponsible typical youngsters to think that hookah is cool, not otherwise.

**Comment by GreenLunar** [comment]
Advertisements in Israel against "nargilla" are nothing new, but before these advertisements, in the late 60's, Israeli Jews HAVE NEVER USED "nargilla", only Arabs.

Again, NO PRESS IS BAD PRESS!

**Comment by GreenLunar** [comment]
Direct link for those who do not use SWF player http://31.168.230.11/flix/buffer/completedFlashFiles/flx87438_200765133183683.flv

**Comment by GreenLunar** [comment]
There is a phrase in Hebrew מים גנובים ימתקו

stolen water tastes sweeter (forbidden things are tempting)

**Comment by GreenLunar** [comment]
@ac-stef please kindly explain why did you close this issue.
