### ISSUE TITLE
Respect XDG base directory specification

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#127]
Do not place all files under `~/.assaultcube_VERSION/`.

Data should be under `~/.local/share/assaultcube/`.
Configurations should be under `~/.config/assaultcube/`.
Cache (demos, too, perhaps) should be under `~/.cache/assaultcube/`.
Screenshots may be under `~/Pictures/AssaultCube/` if not under `~/.cache/assaultcube/`.

See
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
https://ploum.net/207-modify-your-application-to-use-xdg-folders/

**Comment by GreenLunar** [comment]
Data should be under `~/.local/share/AssaultCube/`.
Configurations should be under `~/.config/AssaultCube/`.
Cache (demos, perhaps) should be under `~/.cache/AssaultCube/`, if there is cache in AssaultCube.
Screenshots may be under `~/Pictures/AssaultCube/` if not under `~/.cache/AssaultCube/`.

**Comment by ac-stef** [comment]
Future versions will use ~/.assaultcube/VERSION/ .
AC does not fit into one directory branch specified in that "standard" - and we cannot use multiple directories. We already had that discussion a year ago. Closed.

**Comment by GreenLunar** [comment]
> We already had that discussion a year ago.

Please post a link to that discussion.

**Comment by GreenLunar** [comment]
At least, put everything under `~/.config/assaultcube/VERSION/`.

**Comment by GreenLunar** [comment]
Any comment?

**Comment by GreenLunar** [comment]
AssaultCube is a mess!

Put everything under `~/.config/assaultcube/VERSION/`
Put screenshots under `~/Pictures/AssaultCube/`
