### ISSUE TITLE
The mouse filtering algorithm is bugged

### ISSUE THREAD

**Issue by ghost** [assaultcube/AC#14]
the mouse filtering algorithm AC is using is bugged, I noticed that by enabling it the sensitivity feel changed, indeed the algorithm DOES alter rather unpredictably the total movement resultant...
I propose to change it with this one:

// IN  -----    physics.cpp     --------
// replace this: 
FVARP(mfilter, 0.0f, 0.0f, 6.0f);  
// with this:
FVARP(mfilter, 0.0f, 0.0f, 1.0f);
// and in: 
void mousemove(int odx, int ody)
// replace the older IF clause with this new one:
if(mfilter > 0.0f && mfilter < 1.0f)
{
    float k = mfilter;
    float kdx=fdx-k_(dx+fdx);  dx=dx+kdx;  fdx=fdx-kdx;
    float kdy=fdy-k_(dy+fdy);  dy=dy+kdy;  fdy=fdy-kdy;
}

this algorithm smooths the mouse signal, but still preserves the total movement resultant.
I hope the patch is adopted, since I (and many others) have only access to a cheap mouse...

**Comment by drian0** [comment]
Is this still an issue with modern hardware?
