### ISSUE TITLE
No flag on map in HTF

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#140]
Play HTF on a map without CTF bases.  Flag is always unseen for teammates too.

**Comment by aurhat** [comment]
Thanks, fixed. :)

**Comment by GreenLunar** [comment]
I ask the following, just in case.

Each flag, in maps without CTF bases in play mode HTF, is visible to its respective teammates, not to everyone, am I correct?

**Comment by aurhat** [comment]
Yes, when it's "stolen", and visible for everyone, when it's dropped.
