### ISSUE TITLE
Reload should be slower when health is lower

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#149]
I think reload time should be correlated with health rate.

**Comment by ac-stef** [comment]
Aside from the fact, that gameplay changes are not really discussed atm... lower health makes you easier to be killed, not slower.
If it would make you slower, reload time would not be the most important thing to be affected. If you want to aim for that kind of "realism", you would have to slow down running speeds first - and I really hope, you know, what can of worms that would open up...

**Comment by GreenLunar** [comment]
> I really hope, you know, what can of worms that would open up...

Thinking about it again, yes, that's true.
Though, this can be added as an option for players who want to have this mode on their servers.
