### ISSUE TITLE
Akimbo pickup sound should not be heard by other players

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#150]
Akimbo pickup sound should be heard only by the player that picks it.

**Comment by ac-stef** [comment]
IMO the configurable setting, if picking up the akimbo should switch your weapon or not, should be gone. The akimbo is as much a powerup as it is a game hazard to avoid. On purpose.

**Comment by GreenLunar** [comment]
I did not understand your comment.

**Comment by drian0** [comment]
It is on purpose that picking it up is heard by enemy players. As stef said it is both a powerup and a hazard.

**Comment by GreenLunar** [comment]
Thanks for closing this ticket.
That is to say, I disagree with my past-self.
Cheers!
