### ISSUE TITLE
Look to the right and to the left

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#153]
Allow players to look (spin head, not body) to the right and to the left.  Player can run straight and look to the right or to the left while running to the same direction.  Assigning Back/Forward (intended for browsers) of mouse, when available, would be a good default for this task.

In DukeNukem3D, it is possible to do so using keys <kbd>Insert</kbd> and <kbd>Delete</kbd>  (and aim up and down with <kbd>Home</kbd>, <kbd>End</kbd>, <kbd>PgUp</kbd> and <kbd>PgDown</kbd>, but this is already possible).

**Comment by ac-stef** [comment]
Players can look in eight directions while running. What you want, is to be able to shoot somewhere without looking. IMO that runs completely contrary to the goal of being an arcade-style FPS.

Also, you should make your peace with the concept, that some limitations are intentional.

**Comment by GreenLunar** [comment]
> What you want, is to be able to shoot somewhere without looking.

I don't want that explicitly, though according to my request it is possible.

- Assume you are on defense on a CTF round.
- There are several areas where enemies can get their way to your flag.
- You are directed to a critical spot from which an enemy might come from.
- You do not want to deviate from your current aim.

- Assume you are on defense on a CTF round.
- There are a couple areas where enemies can get their way to your flag.
- You aim to one direction and watch to another direction.
- Once you are being hit by someone you currently do not see, you start to shoot and stop watching to the sides.

Both cases, that may also appeal to HTF, T/KTF, T/OSOK, would better game-play, especially against the proficient players.

> Also, you should make your peace with the concept, that some limitations are intentional.

This is understandable.
