### ISSUE TITLE
AssaultCube error (11) - Crash while multiplayer playing

### ISSUE THREAD

**Issue by pizzamaker** [assaultcube/AC#155]
While using the latest git version. I get the same error when using the latest stable release.

>  assaultcube.sh 
parsing commandline argument 1: "--home=/home/pizzaiolo/.assaultcube_v1.2"
Using home directory: /home/pizzaiolo/.assaultcube_v1.2/
parsing commandline argument 2: "--init"
writing to file: /home/pizzaiolo/.assaultcube_v1.2/clientlog.txt
init: sdl (1.2.15)
init: net (1.3.6)
init: world (1202)
init: video: sdl
init: video: mode
init: video: misc
init: gl
Renderer: Mesa DRI Intel(R) Sandybridge Mobile  (Intel Open Source Technology Center)
Driver: 3.0 Mesa 11.2.0
init: console
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
init: sound
Audio devices: OpenAL Soft
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=Arquivo ou diretório não encontrado)
attempt to connect to server failed
Sound: OpenAL Soft / OpenAL Soft (OpenAL Community)
Driver: 1.1 ALSOFT 1.17.2
init: cfg
init: models
init: curl
init: docs
init: localconnect
read map packages/maps/official/ac_avenue.cgz rev 21 (27 milliseconds)
ac_avenue by jiba
loaded textures (674 milliseconds)
loaded mapmodels (1229 milliseconds)
loaded mapsounds (887 milliseconds)
game mode is "TDM"
init: mainloop
libpng warning: iCCP: known incorrect sRGB profile
connecting to Calinou [Europe/Paris]
attempting to connect to 89.234.181.48:28763
connected to server
read map packages/maps/official/ac_scaffold.cgz rev 2 (4 milliseconds)
ac_scaffold by DogDancing
loaded textures (250 milliseconds)
loaded mapmodels (204 milliseconds)
loaded mapsounds (228 milliseconds)
game mode is "TDM"
Team Deathmatch: Shred the enemy team to pieces!
time remaining: 7 minutes
connected: GTA
connected: SQUEZZIE
MOTD:
Welcome to Calinou's server, hosted in Paris, France.
SQUEZZIE shredded GTA
stacktrace:
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x4b5a3b]
/usr/lib/libc.so.6(+0x33330) [0x7f2fe706e330]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x4765b0]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x472ebd]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x47232d]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x478794]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x46bc48]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x46c061]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x4aa83f]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x46427c]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x4496ac]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f2fe705b710]
/home/pizzaiolo/Jogos/AC/bin_unix/native_client() [0x40e6f9]
AssaultCube error (11) ()
OpenAL Error (A004): invalid operation, line 369
OpenAL Error (A004): invalid operation, line 369
OpenAL Error (A004): invalid operation, line 369
OpenAL Error (A004): invalid operation, line 369
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by ac-stef** [comment]
pls come to #assaultcube on quakenet
(or you can go ahead and provide more details here)

**Comment by pizzamaker** [comment]
This bug was solved by self-compiling assaultcube-next with the command make ACDEBUG=yes install
