### ISSUE TITLE
Nested Demo menu

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#158]
Please allow to read sub directories in `/demo` directory.

I have categorized demos by `/bugs`, `/cheaters` and `/rare` and I would like to access these sub directories respectively.

Also, when the amount of demo files get larger, there is a lag upon opening Demo menu.

**Comment by aurhat** [comment]
In "next" branch there is already implemented similar solution, you can add tag/description to demo and later filter/search demos only with this tag.

**Comment by GreenLunar** [comment]
Thanks for this information. I would still like to have a nested menu for categorizing demos.
