### ISSUE TITLE
Player becomes invisible when spectating someone who disconnects

### ISSUE THREAD

**Issue by pizzamaker** [assaultcube/AC#160]
How to reproduce this bug: Go to spectator mode; spectate a user; the user then disconnects -> now when you follow another user ou even when you spawn, you can't see the third-person model and its gun, making you invisible to yourself (but not to others).

Happened on GNU/Linux, while using the latest git version (not the stable release on the website).

**Comment by aurhat** [comment]
I can't reproduce it, did it happen in  AC from "next" branch?

**Comment by pizzamaker** [comment]
Correct.

**Comment by aurhat** [comment]
Please add link to screenshot, which shows this bug. :)

**Comment by ac-stef** [comment]
Does it also happen in 1.2.0.2? If not, could you please (git-)bisect the issue?
...or provide some clues on how to reproduce it
