### ISSUE TITLE
doesn't run properly on Asus N552vw 4k screen

### ISSUE THREAD

**Issue by Mohammadsoft98** [assaultcube/AC#165]
i have installed latest drivers, direct x 9 and 12, physx 9 ..., on asus n552vw, tested both graphic cards gtx 960m and intel hd 5400 , but failed to run the game smoothly and without lagging!  i tested different resolutions and minimized quality options but doesn't work

**Comment by aurhat** [comment]
How in Sauerbraten: http://sauerbraten.org/ ?

**Comment by ac-stef** [comment]
AC uses neither directx nor physx. Would you mind providing proper details of your setup? Like OS and version, game version and where you downloaded it, was it a fresh install or updated older version, did it work before and stopped working or did it never work, and so on... you know... details!

Also: what is the exact problem? "doesn't run properly" can basically mean anything...

**Comment by Mohammadsoft98** [comment]
windows 10 enterprise 64bit build  14393
game : AssaultCube_v1.2.0.2 from the official publisher :)
its a fresh install , other games also dont run properly on gtx 960m , i often used intel 5300 instead, but both have problem with AC
its problem was from the start(first install)

**Comment by aurhat** [comment]
Do you have installed drivers to graphic card?

**Comment by Mohammadsoft98** [comment]
of course, for both.

**Comment by ac-stef** [comment]
Did you find a solution? Or did you give up?
(If you found a solution, feel free to post it here. Otherwise we'll close the issue in a while, because it doesn't seem to be AC-specific.)
