### ISSUE TITLE
New Release ?

### ISSUE THREAD

**Issue by throwaway217** [assaultcube/AC#166]
When are we going to see a new release ? Are there any milestones or critical bugs that are stopping it from happening ? The forums aren't really that active but the repository seems ok so I figured I shoud ask here.

**Comment by ac-stef** [comment]
Please don't misuse the issue tracker.

**Comment by throwaway217** [comment]
There is no misuse. It's an inquire about the general output of this project. There hasn't been a release in more than 3 years. Is it a misuse regarding this specifc project ? If yes why is there no guidelines when one attempts to make a new issue ?
