### ISSUE TITLE
No desktop file

### ISSUE THREAD

**Issue by tintou** [assaultcube/AC#170]
It seems like debian is providing a patch to AssaultCube in order to ship a .desktop file, it would be better to have this file directly inside the master branch

**Comment by ac-stef** [comment]
AFAIK debian maintainers are not allowed to ship fixes upstream...

**Comment by tintou** [comment]
Is it a joke :p or am I supposed to provide a pull request ?

**Comment by ac-stef** [comment]
It's more of an observation. A link would be fine, thx.

**Comment by tintou** [comment]
Here it is:
https://anonscm.debian.org/cgit/pkg-games/assaultcube.git/tree/debian/assaultcube.desktop

**Comment by ac-stef** [comment]
We already have a script that creates that file:
https://github.com/assaultcube/AC/blob/next/install_or_remove_menuitem.sh
(Not in master, yet, but master will soon be renamed "legacy1.2" while "next" will become master)

Also, I took the liberty of rifling through the patches (https://anonscm.debian.org/cgit/pkg-games/assaultcube.git/tree/debian/patches)...
Why patch the binary to default to windowed mode? We have a commandline switch for exactly that purpose...
