### ISSUE TITLE
Master server 

### ISSUE THREAD

**Issue by DarlyG** [assaultcube/AC#172]
doesn't that multiplayer play

**Comment by DarlyG** [comment]
doesn't that multiplayer play

**Comment by aurhat** [comment]
Probably your IP is in banned range or you don't use the newest 1.2.0.2 version or http://forum.cubers.net/thread-8600-post-169663.html#pid169663 . 
Anyhow please join #assaultcube channel: http://assault.cubers.net/irc.html to get help in fixing the problem, here is not proper place for such reports.
