### ISSUE TITLE
Random Camera Movement

### ISSUE THREAD

**Issue by Highspeedtrain2** [assaultcube/AC#179]
https://streamable.com/r5xgd
1024 by 768 (4:3)
windowed
default computer resolution is 1600 by 900 (16:9)
happens on any resolution i try
any graphics quality
OS: Windows 10 (Falls update)

**Comment by ahrherrera** [comment]
Hi, It happens since I upgraded to Fall Creators Update

**Comment by aurhat** [comment]
There is a fix: https://github.com/assaultcube/AC/releases/tag/v1.2.0.2

**Comment by ahrherrera** [comment]
Thank you @aurhat

**Comment by Highspeedtrain2** [comment]
ayy thanks!

**Comment by aurhat** [comment]
Open - easier to find. :)

**Comment by aurhat** [comment]
Fixed in Windows 10 April 2018 Update
