### ISSUE TITLE
Game Textures at horrible Quality.

### ISSUE THREAD

**Issue by ZenixPlays** [assaultcube/AC#180]
I downloaded the game and when it opens, the menu, Crosshair, the weapons, the map, the characters, everything! is in a deplorable quality.
![bug](https://user-images.githubusercontent.com/33501925/32581841-7998e49a-c4ca-11e7-97de-b6d520c78751.png)

**Comment by zeSKB** [comment]
If i'm not mistaken, you need to reduce mipmapping in your gpu driver to a more sane level.

**Comment by ZenixPlays** [comment]
@zeSKB Ok How i do that?

**Comment by ZenixPlays** [comment]
Ok but i don't know how reduce the mipmapping

**Comment by ZenixPlays** [comment]
Thanks, That solved my problem

**Comment by ac-stef** [comment]
What graphics card, OS and driver do you use? Do you remember fiddling with driver settings before or was the bad mipmapping setting the driver's default setting?

**Comment by aurhat** [comment]
Specs from Assasin, which had similar problem and above solution helped (he rather didn't change the default mipmapping settings before the problem appearance): https://imgur.com/urbrhsa

**Comment by Calinou** [comment]
To solve this, the renderer should explicitly force the mipmap LOD bias to 0. I'm not sure if OpenGL 1.x exposes a way to do this though.
