### ISSUE TITLE
it won't load

### ISSUE THREAD

**Issue by CyberShinobi** [assaultcube/AC#185]
there is no AC.exe file in the bin...

not the exact file name...

**Comment by aurhat** [comment]
Run assaulcube.bat or use shortcut on the desktop/menu with programs.

**Comment by CyberShinobi** [comment]
i got it off github and there was no assultcube.exe the assultcube.bat loads
but then it says there is no assultcube.exe in the bin for the .bat to
load... thanks for your help though...

**Comment by zeSKB** [comment]
You did not download the release - it's just development files you have there. You want 'AssaultCube for Widows' from here: https://github.com/assaultcube/AC/releases/tag/v1.2.0.2

**Comment by CyberShinobi** [comment]
Thanks!
