### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [assaultcube/AC#188]
I'm on arch linux operating system and    when i playing at the game , it's the  game crash. 
Can you fix this problem ?

**Comment by aurhat** [comment]
https://github.com/assaultcube/AC/pull/159 - Arch packagers can fix it. 
You can use vanilla binary from https://assault.cubers.net/download.html / https://github.com/assaultcube/AC/releases/tag/v1.2.0.2

**Comment by fumseck** [comment]
how Arch packagers can fix it ?

**Comment by aurhat** [comment]
The presumable reason is that they used system enet library, instead of this from enet sources included in AssaultCube package, so therefore AC crashes.

**Comment by fumseck** [comment]
/home/fumseck/Téléchargements/AssaultCube_v1.2.0.2/bin_unix/linux_64_client: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/fumseck/Téléchargements/AssaultCube_v1.2.0.2/bin_unix/linux_64_client)

**Comment by aurhat** [comment]
sudo pacman -S libcurl-compat ?

**Comment by fumseck** [comment]
yes i've run it

**Comment by fumseck** [comment]
if it can help on linux mint the game work normaly

**Comment by aurhat** [comment]
With libcurl-compat library you can run vanilla AC on Arch?

**Comment by fumseck** [comment]
Sorry i don't understand wath it's vanilla

**Comment by aurhat** [comment]
Default binary, delivered in the official package - not self-compiled

**Comment by fumseck** [comment]
yes i can run AC on arch

**Comment by fumseck** [comment]
i can play but it crash always

**Comment by aurhat** [comment]
You can download now AC 1.2.0.2 supporting libcurl4 from https://assault.cubers.net/download.html (currently that is default package for Linux), see more on https://github.com/assaultcube/AC/releases -> "Important information for Linux users".
