### ISSUE TITLE
Multiplayer ISSUE

### ISSUE THREAD

**Issue by DOPEEEEE** [assaultcube/AC#189]
When I try to go on to multiplayer on assault cube all the servers show up, but doesn't let me in. Then I deleted assault cube and reinstalled it, when I opened it again, I quickly went to multiplayer after the settings, and once I opened multiplayer... No servers showed up! It kept on telling me to go to this link to see a problem.

**Comment by DOPEEEEE** [comment]
Please help me with this situation, thanks. ~DOPEEEEE

**Comment by Ir0z** [comment]
Are you d0pe from Hunt ?

**Comment by aurhat** [comment]
What is your in-game nick (you can send me PM on AC IRC/Discord channel)?
