### ISSUE TITLE
Images in readme

### ISSUE THREAD

**Issue by ritwik12** [assaultcube/AC#195]
It looks amazing but I guess few screenshot images of the game in readme or a link to its website in the description will be good.

**Comment by Rivest8** [comment]
Like these? I grabbed them off the website.
 If someone wanted they could use the links here or from the website to do this.

![cla-rvsf](https://user-images.githubusercontent.com/7680684/69888831-96ff9680-12b3-11ea-9094-8c650c919620.png)
![aclogo](https://user-images.githubusercontent.com/7680684/69888835-98c95a00-12b3-11ea-8570-5392aff3f21b.png)
![screenshot-table](https://user-images.githubusercontent.com/7680684/69888836-9a931d80-12b3-11ea-8123-bbf06908a96f.jpg)

**Comment by ritwik12** [comment]
@Rivest8 Yeah, that will be good.
