### ISSUE TITLE
libcurl.so.4: version `CURL_OPENSSL_3' not found

### ISSUE THREAD

**Issue by yorksgomez** [assaultcube/AC#196]
Im getting this error when i try to start AC in Linux (Lubuntu).

**Comment by aurhat** [comment]
Try to install assaultcube using apt, later you should be able to run AC from https://assault.cubers.net/download.html

**Comment by asm-pas** [comment]
I know what happened there, in order to use CURL_OPENSSL4 you need to to remove CURL_OPENSSL3, which is done automatically to prevent the system issues, and if you revert it, it will remove CURL_OPENSSL4 which is required in ubuntu 17.04 and above... installing it using apt will solve this issue

**Comment by ZeroCoolHacker** [comment]
How to install it from apt? there is no way to install the game with apt. i don't seem to find it.

**Comment by ZeroCoolHacker** [comment]
I really want to play this game. I am having the same issue but i don't want to remove curlssl4 kindly guide me to change some config file maybe to use curlssl4

**Comment by aurhat** [comment]
@ZeroCoolHacker What Linux distribution?

**Comment by ZeroCoolHacker** [comment]
Debian
Kali Linux Rolling

**Comment by aurhat** [comment]
OK, in Debian repository there is only old 1.1.0.4 version, which didn't use curl yet (it is needed by v. 1.2). So you will be able to play AC on Debian if you will compile "master" branch, because it already doesn't use curl.

**Comment by ymartin59** [comment]
Same issue here. 1.2.0.2 binaries for Linux x64 does not run on Debian Testing - same error message. I have both libcurl3-gnutls and libcurl4 (I would say it contains both openssl and gnutls versions) installed. Any hint how to work-around this startup failure?

**Comment by aurhat** [comment]
You have to compile "master" or "experimental" branch.

**Comment by ymartin59** [comment]
Hum... from my point of view, it sounds faster to rebuild libcurl with proper prerequisites so that AC runs. What was libcurl version/from which distribution AC binary has been built against?

**Comment by aurhat** [comment]
I don't know (I wasn't in dev team then). During compiling v. 1.2.0.2 in newer distributions there are some errors, which of course can be fixed, but just compiling "master"/"experimental" branch is faster.

**Comment by aurhat** [comment]
You can download now AC 1.2.0.2 supporting libcurl4 from https://assault.cubers.net/download.html,
see more on https://github.com/assaultcube/AC/releases -> "Important information for Linux users"

**Comment by onion-overdose** [comment]
I am getting the same error on executing assaultcube.sh (from AC 1.2.0.2) on Manjaro.

**Comment by aurhat** [comment]
Could you check below binaries (compiled on Debian 10 Buster):
https://github.com/assaultcube/AC/releases/download/v1.2.0.2/AssaultCube_v1.2.0.2_libcurl4.tar.bz2 ?

**Comment by drian0** [comment]
This should be fixed in the upcoming version was libcurl has been replaced.
