### ISSUE TITLE
Install server from source

### ISSUE THREAD

**Issue by symbios24** [assaultcube/AC#199]
Hello there

I`m Trying to make an assault cube server but im trying to do it from source
eg: git clone  https://github.com/assaultcube/AC
and not by downloading the files since the files are dated from 2013 and the source from 2018
are there any instructions about?
all the info i can find online is only by build from the download files :

AssaultCube_v1.2.0.2.source.tar.bz2
AssaultCube_v1.2.0.2.tar.bz2

Thank you

**Comment by ac-stef** [comment]
try branch legacy1202

**Comment by symbios24** [comment]
thanks what do you mean how to try that?

**Comment by symbios24** [comment]
one thing if i uninstall clang after i installed the server will the server still work?

**Comment by ac-stef** [comment]
Sure. If you uninstall the compiler, you simply can't compile anymore.

If you're trying to preserve disc space, it would have made more sense to download a zip instead of cloning the full repo, though.
