### ISSUE TITLE
No 64bit MacOS Binary

### ISSUE THREAD

**Issue by ReagentX** [assaultcube/AC#201]
32bit support is deprecated in MacOS 10.15 Catalina, which means the current AC build will no longer run.

**Comment by aurhat** [comment]
Thanks for information. 
We prepared experimental AC hotfix 64-bit release (more information on https://github.com/assaultcube/AC/releases/tag/v1.2.0.2 ). It would be helpful if somebody would check whether it works on macOS 10.15. :)
PS. Please don't close this issue. :)

**Comment by davepait** [comment]
@aurhat - This doesn't work on macOS 10.15.2 system alert brings you to a page about updating 32bit apps

**Comment by aurhat** [comment]
For 100% you used: https://github.com/assaultcube/AC/releases/download/v1.2.0.2/AssaultCube_v1.2.0.2_experimental_macOS10.15_hotfix_1.dmg ?

**Comment by davepait** [comment]
@aurhat - positive, just re-downloaded to make sure 
<img width="403" alt="Screen Shot 2020-01-07 at 6 14 28 PM" src="https://user-images.githubusercontent.com/47537874/71937193-ace95c80-3179-11ea-80a8-522e6fc999fd.png">
<img width="583" alt="Screen Shot 2020-01-07 at 6 14 38 PM" src="https://user-images.githubusercontent.com/47537874/71937197-b07ce380-3179-11ea-998a-f8d46e24abab.png">
<img width="1046" alt="Screen Shot 2020-01-07 at 6 15 02 PM" src="https://user-images.githubusercontent.com/47537874/71937206-b672c480-3179-11ea-85a2-2f5644dd1a0d.png">
<img width="436" alt="Screen Shot 2020-01-07 at 6 15 10 PM" src="https://user-images.githubusercontent.com/47537874/71937219-bc68a580-3179-11ea-8f7e-e894b8c74b5c.png">

**Comment by aurhat** [comment]
Could you redownload AC and check now? Launcher was compiled as 32-bit application, now it's compiled as 64-bit application.

**Comment by davepait** [comment]
@aurhat - Thanks, this does at least open now but crashes with the below stack trace:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFConstantString substringToIndex:]: Index 18446744073709551615 out of bounds; string length 4'
terminating with uncaught exception of type NSException
abort() called

**Comment by aurhat** [comment]
Does launcher crash or AC, which you start in the launcher?

**Comment by davepait** [comment]
@aurhat - It appears to be the launcher, that error came from an apple crash report. Going into the package contents of the app directly and launcher the AC doesn't work either and also doesn't report any errors/crashes

**Comment by davepait** [comment]
@aurhat - Just to update, I can run it by cd'ing into the app package and running the binarary from there:

cd /Applications/AssaultCube.app/Contents/gamedata
./assaultcube.app/Contents/MacOS/assaultcube

Then it runs, so I'm assuming it's still just an issue with the launcher

**Comment by aurhat** [comment]
@davepait Could you redownload AC package again and check now? It should be already fixed.

**Comment by drian0** [comment]
I am closing this assuming we would run into this during v1.3 testing if the issue still exists.
