### ISSUE TITLE
Implement WebAssembly/WebGL targeting

### ISSUE THREAD

**Issue by fvilante** [assaultcube/AC#202]
**What about target AC to be served on Web Browser ?** 

Some key facts:

- Unreal and [Autocad](https://www.autodesk.com/products/autocad-web-app/overview?linkId=68719474) can be compiled from C++ source to [WebAssembly](https://webassembly.eu/) and get runned into Web Browsers.
- [WebGL](https://www.khronos.org/webgl/wiki/Getting_Started#Key_Advantages) has same API that OpenGL
- [C++](https://dassur.ma/things/c-to-webassembly/) can target WebAssembly using LLVM.

Distribute  it through web should be a game changer. _Excuse me pun_.

I would like to hear from you.

_Thanks to create and mantain this awesome game._

**Comment by auermich93** [comment]
I think this could be really a game changer. However, I have dived a bit into WebAssembly and have the impression that WebAssembly is not yet in the state AC would require. For instance, the network code seems to be not fully convertable to WebAssembly code yet, at least if you consider the problems related to sockets on various forums. Moreover, implementing this feature is quite some engineering effort.

**Comment by drian0** [comment]
It is correct that AC does have dependencies to libraries that currently do not run on WASM. You are welcome to write a prototype and investigate this further. We would be interested to hear your findings!
