### ISSUE TITLE
This is NOT open source but README says it is

### ISSUE THREAD

**Issue by Kimapr** [assaultcube/AC#207]
The license clearly restricts modification and commercial use, something that being open source doesn't allow to restrict. Please remove the "open-source zlib-like license" part from readme or fix the license. The license is far from being zlib-like, more so than being open source at all.

**Comment by Kimapr** [comment]
https://opensource.org/osd

**Comment by aurhat** [comment]
https://github.com/assaultcube/AC/blob/master/source/README.txt

**Comment by Kimapr** [comment]
3 readme files? Are you guys serious?

**Comment by aurhat** [comment]
Well, tradition.
"its license" - what is "its" - AC's? If there is written that license of AC source code is the same as license of Cube source code, that why do you claim that it's not true?

**Comment by Kimapr** [comment]
"its license" = AC's license, README.md links to the restrictive license.
The first readme i see is README.md, so please put correct information in it. This is the first software i saw ever that licensed binaries differently than the source code, and also the first one that stored binaries in a git repo

**Comment by KYHSGeekCode** [comment]
@Kimapr  Hello, just a question, do you mean that projects published with quite strict licenses like GPL are not open source? I thought that any product that disclosure source can be called "open sourced."

**Comment by Kimapr** [comment]
@KYHSGeekCode no, there is an official definition for term "open source", it's not just any product that disclosures source: https://opensource.org/osd

**Comment by divy-work** [comment]
@KYHSGeekCode The open source defination clearly states that:

> Open source doesn't just mean access to the source code

I completely agree with @Kimapr to change the README.md at the root directory. It is misleading.

**Comment by drian0** [comment]
The information provided in the readme is accurate. Simplified, the *source code* is open source while the assets are not. There are historical reasons as well as practical reasons for this.
