### ISSUE TITLE
Post-installation bugs in AssaultCube

### ISSUE THREAD

**Issue by Chief369** [assaultcube/AC#210]
I'm an AssaultCube user in Linux Mint 19.3 Tricia. In my device, if I install the game through Software Manager, I'm not getting the Server Wizard file. On the other hand, when I install it from the official website, the game disappears leaving just the other program and text files after configuring the server through server wizard.  Please help me get rid of this problem. 
#193

**Comment by aurhat** [comment]
https://assault.cubers.net/download.html - could you redownload AC for Linux? Client binary was updated, so it should start correct on the newest Linux systems.
