### ISSUE TITLE
Green lines and a glitched interface

### ISSUE THREAD

**Issue by echometer** [assaultcube/AC#212]
The entire game appears like this:
![image](https://user-images.githubusercontent.com/68754154/88427345-bdcd8880-cdc0-11ea-8451-c09de07d0f58.png)
![image](https://user-images.githubusercontent.com/68754154/88427356-c1f9a600-cdc0-11ea-823f-748360a81b23.png)
I'm using the latest update of windows 10 (19041 as of 7/24/20)
I have an Intel i5-8250U, 8 gb of memory and Intel UHD graphics 620

**Comment by aurhat** [comment]
You should check newer driver for graphic card, web search shows that it's quite common problem.

**Comment by echometer** [comment]
The driver showed it didn't need an update at first, but now I fixed it and the game is working. Thank you!

**Comment by aurhat** [comment]
google UHD 620 green lines - it's quite common problem. And laptop manufactures don't update so often graphics drivers as graphic card manufactures - you have probably older driver than on: https://downloadcenter.intel.com/download/29988/Intel-Graphics-Windows-10-DCH-Drivers?product=96551 (but see the note on that page).

**Comment by haeoro** [comment]
> The driver showed it didn't need an update at first, but now I fixed it and the game is working. Thank you!

How did you manage to fix it? I updated my graphics drivers and it didn't change squat.
