### ISSUE TITLE
Integrate damage per player into score board

### ISSUE THREAD

**Issue by auermich93** [assaultcube/AC#216]
Hi guys,

it would be nice to provide an additional column on the score board that shows how much damage a player has made.
Or, at least the damage performed by a player could be reflected in the scoring system. If you are responsible for 90% of a frag, you should be attributed some part of the score.

**Comment by VoxelTek** [comment]
Yeah, I highly agree.
I was playing AssaultCube today, and I kept checking the scoreboard for my damage count, as this is common in other FPS games I play. However, I understand that it may not be simple to implement, and as this is a minor issue, I would be fine without the damage counter existing.

**Comment by VoxelTek** [comment]
> Or, at least the damage performed by a player could be reflected in the scoring system. If you are responsible for 90% of a frag, you should be attributed some part of the score.

I remember a Minecraft PVP server I was on, which, instead of counting who did the final blow, counted instead who did the most damage overall, and awarded them the kill. Anyone else with more than 1% of damage done to the same person would receive an "assist"

**Comment by auermich93** [comment]
Many other games also incorporate 'assists' in the scoring, e.g. Battlefield. It shouldn't be too difficult to integrate this feature, as all relevant information is already present. For instance, the accuracy script already provides stats like hits per gun, which is sufficient for computing the total amount of damage.

**Comment by aurhat** [comment]
Damage/total damage isn't/wasn't an aim in AC, in my opinion such info doesn't fit to much to AC, at least on scoreboard (which main aim is comparing the stats).

**Comment by auermich93** [comment]
Well, the total damage is rather useless if not compared to any other players, i.e. noone cares about total damage if it can't be compared to anyone else. However, it is not necessarily meant to be a default stat on the scoreboard, rather an optional/configurable one like ratio is. The new scoreboard perfectly fits this stat as it can be fully customized.

**Comment by drian0** [comment]
The scoring system has been removed, please see https://github.com/assaultcube/AC/issues/269
Therefore I am closing this issue. I am sorry that you PR could not be considered for integration.

**Comment by auermich93** [comment]
@drian0: If you intend to integrate it in the future, I can try to fix the remaining issues.

**Comment by acrobtics** [comment]
atm this is done by using a script as workaround. an official way to track stats like dmg would be nice to have

**Comment by auermich93** [comment]
But before we should discuss what we exactly want:

1. Solely the total damage displayed on the scoreboard as a dedicated column.
2. A combined metric of damage and score, i.e. interweaving the damage into the scoring computation.
3. A more fine grained computation that shows damage per gun, i.e. extending the accuracy display with this information.

**Comment by auermich93** [comment]
Here is a possible implementation for multiplayer mode: https://github.com/auermich93/AC/pull/1
