### ISSUE TITLE
recoil is insane

### ISSUE THREAD

**Issue by iAmBigNerd** [assaultcube/AC#224]
everything is good, but can you lower the recoil a little bit on automatics? it's not very realistic and it kind disturbs me. but everything else is amazing keep it up!

**Comment by AC-Panda** [comment]
Recoil was actually implemented for added realism ... Also, recoil can be very helpful in making quick escapes vie rifle-sprinting, or reaching tall heights with rifle-jumping. Techniques are explained in the official AssaultCube documentation.
https://assault.cubers.net/docs/maneuvers.html

**Comment by iAmBigNerd** [comment]
> Recoil was actually implemented for added realism ... Also, recoil can be very helpful in making quick escapes vie rifle-sprinting, or reaching tall heights with rifle-jumping. Techniques are explained in the official AssaultCube documentation.
> https://assault.cubers.net/docs/maneuvers.html

That makes a lot more sense. I saw the maneuvers and it actually helps me a lot!
