### ISSUE TITLE
audio

### ISSUE THREAD

**Issue by iAmBigNerd** [assaultcube/AC#226]
Almost every time, during mid-game the audio would just completely go off. I would not have changed anything and it would completely stop. Is it just me or is anyone else having this problem?

**Comment by AC-Panda** [comment]
This is a known bug. Fix it by doing the command in-game **/bulletairsound 0**.

**Proof/Info**
https://wiki.cubers.net/action/view/FAQ#The_sound_keeps_disappearing_on_Windows

**Comment by drian0** [comment]
@aurhat You mention that this is fixed in dev. Will we go with openal-soft by default? Or has the fix been achieved through some other way? Thanks for the info.
