### ISSUE TITLE
Illegal characters inside map config files cause crash

### ISSUE THREAD

**Issue by NadalB** [assaultcube/AC#233]
included map for test : https://mega.nz/file/BzYBTSqb#3yFmMwtLd2DWXCfzihpJPvOcQ7Z9In5klu4GbyZqSZw
tested near all branches and got the same result.

**Comment by aurhat** [comment]
On what system? No crash on Linux.

**Comment by NadalB** [comment]
windows 10 20H2( i dont know that makes any difference )

**Comment by NadalB** [comment]
Solved on using static atl
