### ISSUE TITLE
[release_1.3] using "oldfashionedgunstats" appears two grenade icons

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#237]
![20210331_16 14 56_dev_desert_TDM](https://user-images.githubusercontent.com/7694535/113180156-c8310380-9226-11eb-9de9-08c822f19d42.jpg)
problem is here, [Fix grenade icon alignment for enabled oldfashionedgunstats](https://github.com/assaultcube/AC/commit/db18caba1673fb770233aa0fe68c2bd591c4333b)

with the additions missing from the grenadier this will be fixed.

**Comment by flowtron** [comment]
fixed in https://github.com/assaultcube/AC/commit/b5a5f7bed9a5b0f166bef1efcd1b056919b73002
