### ISSUE TITLE
[release_1.3] coop: in long distance new clips appear behind the walls, but when you get a little closer it doesn't happen

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#238]
![20210331_16 14 59_dev_desert_TDM](https://user-images.githubusercontent.com/7694535/113181833-94ef7400-9228-11eb-81dd-38a2f8c4f44d.jpg)
![20210331_16 15 05_dev_desert_TDM](https://user-images.githubusercontent.com/7694535/113181880-a3d62680-9228-11eb-8134-8368a30400a0.jpg)
it doesn't interfere with anything, just reporting.

**Comment by drian0** [comment]
I think this is OK. We can reopen this if someone disagrees...
