### ISSUE TITLE
Assault Cube server crashes whenever players try to upload a custom map for editing or play

### ISSUE THREAD

**Issue by blehmeh98** [assaultcube/AC#240]
Hello,
I'm having some fun hosting an Assault Cube server on a VPS I own. However, the server crashes whenever anyone other than me attempts to send a custom map to the server. Here's the relevant error from the log.

```
Game status: deathmatch on ac_wasteland, 3 minutes remaining, open, 2 clients
cn name              score frag death ping role    host
 1 PeterGalax           25    8    15  163 normal  189.123.125.175
 5 Bulldog             172   20     7  164 normal  187.11.24.6

Status at 30-03-2021 20:22:34: 2 remote clients, 2.3 send, 1.6 rec (K/sec); Ping: #21|1262|42; CSL: #0|0|0 (bytes)
waking readmapsthread
[189.123.125.175] PeterGalax picked off Bulldog
[80.145.72.145] client connected
[80.145.72.145] ChlefGaming logged in (default), AC: 1202|c44
[41.44.95.110] client connected
[187.11.24.6] Bulldog splattered PeterGalax
[41.44.95.110] fdg logged in (default), AC: 1202|c04
[80.145.72.145] ChlefGaming sent map ac_unarmed_gema rev 25, rejected: write failed (no 'incoming'?)
stacktrace:
./bin_unix/native_server() [0x43c96a]
/lib/x86_64-linux-gnu/libc.so.6(+0x37840) [0x7fa10df2c840]
./bin_unix/native_server() [0x4114e6]
./bin_unix/native_server() [0x426ab9]
./bin_unix/native_server() [0x42d187]
./bin_unix/native_server() [0x42e5ca]
./bin_unix/native_server() [0x42e659]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fa10df1909b]
./bin_unix/native_server() [0x40408a]
ERROR: AssaultCube fatal error: AssaultCube error (11)
```

The server completely crashes, and I have to reconnect to the VPS over SSH and relaunch the server. 

I have already tried a little bit of testing and solutions.

- I noticed that root owned all the files for the server and the maps and the like, when I was running the server under a non-root user account. I changed ownership of every file related to the assault cube server from root to said user.
- I made sure the file permissions for the maps folder, especially the "incoming" folder, allowed for reading and writing by the user who owns the file (yes, the user running the server).
- I tried uploading my own maps. I would make a map with the /newmap command, mess with some of the terrain and make a few lights, walls, and spawnpoints, save it with a unique name, and upload it to the server. This works great and doesn't crash the server. I've tried doing this from both the player identity with admin privileges, and an entirely unique player identity without admin privileges, and I've never had the server crash on me because of this.
- When all these errors were happening, I had the coop-edit permisions set to "cURP" (anyone can upload a map, but only admins can update it, revert it, or delete it). 
- I have the custom map max size set to the default of 10 MB. I don't want people flooding my server with insanely bloated maps or something. I think 10 MB should be enough if it's the default size. Is it? I'm not getting any errors about the map being too big, just errors that there is no "incoming" folder even though there very clearly is.

I don't get this error and I feel like I have exhausted my options to fix it. The incoming folder certainly exists and is in the right place, and I've even been successful in uploading maps myself from various different Assault Cube identities and various different maps. 

Does anyone have any idea what the issue is?

More information for more context:

- I'm running a Debian 10 server
- I downloaded the main repository for Assault Cube and compiled it straight on the server in order to run the server.

**Comment by drian0** [comment]
Thank you for this report. We could not reproduce this issue unfortunately.
Could you please send us your servercmdline.txt and could you please confirm that you are using the official binaries?

**Comment by AC-Panda** [comment]
Possibly unconverted 1.0 maps on a 2.0 server.
