### ISSUE TITLE
[release_1.3] reproducing pain sound when pressing ( ç ) and ( ´ )

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#242]
this occurs when opening chat and in menus that it is possible to write.
[bug video](https://drive.google.com/file/d/1O73c2qvP5efcRSbA-PJrOIalNAFqN0Qj/view?usp=sharing)

I checked branch stef ac_next, it doesn't happen there, maybe it has already been fixed in another branch.

**Comment by drian0** [comment]
This has been added on purpose, please see
https://github.com/assaultcube/AC/commit/e75dfbe4c73500d9e4175f2b1c6c6d5ea8393f17
in console.cpp 604

I understand that this functionality may confuse players. 
I will reach out to grenadier to discuss this.

**Comment by BrutalSystem** [comment]
really confuses, instead use echo or hudecho to show this information

**Comment by drian0** [comment]
I disabled the sound for now and once we have a better sound we can re-enable it.
