### ISSUE TITLE
[release_1.3] menu back-navigation is not standardized

### ISSUE THREAD

**Issue by drian0** [assaultcube/AC#243]

**Comment by drian0** [comment]
There are different approaches in place how to navigate "back" in the menu. Sometimes there is an explicit "back" button in the menu and sometimes it is expected to simply press the ESC key to navigate back. This should be standardized.

Applies to:
    config/menus_edit.cfg:menuitem "\f2Back" [ closecurmenu ]
    config/menus_multiplayer.cfg:menuitem "\t\t[Not now...]" closecurmenu


Furthermore, the video menu should not reset GL if closed with ESC.
    config/menus_settings.cfg:menuitem "\f2\t\t\t        [ OK ]" [ closecurmenu; resetgl ]

**Comment by BrutalSystem** [comment]
@drian0 MOUSE2 works like ESC.
