### ISSUE TITLE
[release_1.3] *accuracy* when taking damage from your own grenade, should accuracy compute that information?

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#245]

**Comment by drian0** [comment]
@BrutalSystem This one is a bit unclear for me. Could you please post a screenshot or describe it in more detail?

**Comment by drian0** [comment]
I think that people that use the 'accuracy' stats want to know how effective they are in combat and therefore the damage taken from your own grenade should not count toward that stat.
