### ISSUE TITLE
[release_1.3_alpha1] map locations that need to be fixed

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#247]
some places are where you can pick up the flags on the other side of the wall, others are where you can drop the flag so no one can pick it up (having to wait 30s until it automatically returns to the base.

OBS: keep this issue open so i can continue updating if i find another place

![20210409_00 10 57_ac_shine_CTF](https://user-images.githubusercontent.com/7694535/114111463-79334000-98b0-11eb-8a30-f7889105ba33.jpg)
map: dev_shine
![20210409_00 12 16_ac_elevation_CTF](https://user-images.githubusercontent.com/7694535/114111465-79cbd680-98b0-11eb-94f2-717f16f4cb8a.jpg)
map: dev_elevation
![20210409_00 12 24_ac_elevation_CTF](https://user-images.githubusercontent.com/7694535/114111468-7afd0380-98b0-11eb-9ac1-31d5552cb286.jpg)
map: dev_elevation
![20210409_00 13 58_dev_dusk_CTF](https://user-images.githubusercontent.com/7694535/114111469-7b959a00-98b0-11eb-88c9-536826209cd4.jpg)
map: dev_dusk
![20210409_00 14 27_dev_toxic_TDM](https://user-images.githubusercontent.com/7694535/114111471-7cc6c700-98b0-11eb-95b5-1728c4e2bc3c.jpg)
map: dev_toxic
![20210409_00 14 58_ac_power_CTF](https://user-images.githubusercontent.com/7694535/114111473-7cc6c700-98b0-11eb-8c68-c2f908d346c6.jpg)
map: dev_power

**Comment by drian0** [comment]
@BrutalSystem Could you provide a short update on this one?

**Comment by acrobtics** [comment]
there are definately a lot of spots missing where you can pass flags through walls / slash through walls.

**Comment by BrutalSystem** [comment]
fixed, hoping the rest is fixed with code, if that's not possible I fix what's missing before the release.

**Comment by drian0** [comment]
Thank you very much. I closed this issue. If there are further issues please create new/additional issues on github so that we can track it individually. Thanks.
