### ISSUE TITLE
[release 1.3] some problem with adding Pause

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#250]
![20210415_01 12 28_ac_scaffold_TDM](https://user-images.githubusercontent.com/7694535/114799838-f2c6a480-9d6e-11eb-93b0-4e560370934e.jpg)
1) "gametimedisplay 1" now shows negative time.
2) time is not really paused (time keeps running, but time will stop, and wrong time will be shown, when the minutes of the map pass, the map will come to an end.

test example: vote map and pause game, wait for the map time to end, then resume game.

3) It is possible to use the suicide command.
4) it is possible to change weapons "but this only happens when the vote to resume (pause 0) is accepted".
5) time of dropped flags do not stop.
6) pickups respawn time do not stop.
7) while dead "you can rotate camera with the mouse".
8) KTF: if you have the flag, you will score points, as the scoring time do not stop.
9) HTF: flag will go to someone time do not stop.
10) TSURV/SURV/TOSOK/OSOK: time of the round not stop (if everyone dies, "next round in 5 seconds").
11) TDM/DM: while dead, you will automatically respawn (you are forced to respawn in these modes, it’s not like in the CTF, where you have to click to respawn).
12) it is possible to drop flag.
13) spectator players can respawn (it may be good to allow only "benchme" players), but that doesn’t stop spectators from going to benchme and then respawn.

**Comment by drian0** [comment]
I think point 7 is acceptable, what do you think?

**Comment by drian0** [comment]
@BrutalSystem Please let me know should you encounter any other issues related to this. I am closing this for the moment.

**Comment by BrutalSystem** [comment]
> I think point 7 is acceptable, what do you think?

my opinion is, it is not acceptable, because the intention of the pause is to pause everything to maintain a fairer competitive match for both teams, those who play competitive usually use Discord to communicate with their team with voice. then someone could communicate the enemy's position to his team.

> @BrutalSystem Please let me know should you encounter any other issues related to this. I am closing this for the moment.

@drian0 everything fixed, I hope I haven't forgotten something.

14) I forgot to mention change to the enemy team
note: i think the vote should be ignored (force yourself to enemy team and force a team change)

15) W, S, D and A reproduce sound as if you are walking, I don't know if anyone else can hear the sound.

**Comment by drian0** [comment]
7. I understand the rationale. I disabled it now.
14. Why would you allow certain votes but not others?
15. I resolved this.

> I think you should not resume the game immediately, there should be a 5s counter so that everyone can have time to prepare for the resume, the counter could be similar to the one that warns you that you can respawn

Yes that would be nice. However this would introduce another complexity as you would need to properly handle that timer for new clients that join the game during that period. It might even require a protocol change. I'd prefer if we could keep it simple for the moment.

**Comment by BrutalSystem** [comment]
> 1. I forgot to mention change to the enemy team
>    note: i think the vote should be ignored (force yourself to enemy team and force a team change)

> 2. Why would you allow certain votes but not others?

because you will call voting to change sides, depend on other people to change sides, it will not happen istantaneo. so I don't think it's necessary to touch it.

"change to the enemy team" it's not a vote, you just choose to change sides <-this is instant
"force yourself to enemy team and force a team change" are vote.

**Comment by drian0** [comment]
So could we simply prevent "change to enemy team" during pause and leave the other actions as-is? Do I understand you correctly?

**Comment by BrutalSystem** [comment]
> So could we simply prevent "change to enemy team" during pause and leave the other actions as-is? Do I understand you correctly?

exactly
