### ISSUE TITLE
Question about the algorithms in the AC

### ISSUE THREAD

**Issue by WilliamWangPeng** [assaultcube/AC#252]
HI dear author,
It's truly a honor to write a letter to you,  
  Could you please tell me what kind of algorithms in the assaultcube :)

thank you
best regards to you
William

**Comment by drian0** [comment]
Hello William, there are several algorithms in place in a game engine. What sort of algorithm are you interested in?

**Comment by WilliamWangPeng** [comment]
> Hello William, there are several algorithms in place in a game engine. What sort of algorithm are you interested in?

Hi dear @drian0   
    Could you please give me five names of the algorithms in assaultcube and I will present this game with algorithm in the conference, algorithms like billboard.  :)  

thank you  
best regards  
William

**Comment by drian0** [comment]
There are many different algorithms in place at different levels. I would need to scan through some of the code and randomly pick algorithms without knowing if they fit the target audience of your conference. Unfortunately I currently do not have time to provide you this service. I am sorry.
