### ISSUE TITLE
[release_1.3_alpha1] right click nade is slow

### ISSUE THREAD

**Issue by drian0** [assaultcube/AC#254]
steps:
- pick up a nade
- right-click to throw it

expected:
duration/responsivenes of this action is the same as in AC v1.2

actual:
the duration/responsiveness of this action is slower than AC v1.2

source: XRD

**Comment by BrutalSystem** [comment]
https://github.com/assaultcube/AC/commit/d3bd26a62d2e83b03dcea1a5f1ed320e671605fe#diff-cda74301709d93989ed36eb85d18599c7a15159964458a7f492582cdb5c57fd6

**Comment by drian0** [comment]
I reverted this because there seems to be consensus that the old behavior needs to be restored. On a sidenote, from the perspective of a new player the quick nade throw animation looks pretty buggy to be honest so I fully understand why it was fixed/changed in the first place.

The changed behavior has been reverted with commit d3bd26a. I am closing this. 

Feel free to reopen or provide a PR if you want to rectify the animation.
