### ISSUE TITLE
[release_1.3] address FIXME in crypto

### ISSUE THREAD

**Issue by RonaldReagan** [assaultcube/AC#256]
Two related FIXME's in the codebase. First one should be easy, second might require more thought.

There is a fixme indicating that some code should be removed before release. We should remove this code. crypto.cpp:913
```
        else if(!strcasecmp(args[0], "UNARMED"))  // FIXME: this is for testing purposes only - to test simultaneous logins from the same account - delete before release!
        {
            // authsetup unarmed
            // pub aa55aab6d746c2000f3f6dc133c49c5d0485e0e44cbf036757e7945bca20106f  priv aa55aa55aa55aa55aa55aa55aa55aae5a973aa55aa55aa55aa55aa55aa55aa55
            hex2bin(priv, "aa55aa55aa55aa55aa55aa55aa55aae5a973aa55aa55aa55aa55aa55aa55aa55", 32);
            ed25519_pubkey_from_private(pub, priv);
            privpwdcfg = 0;
        }
```

This fixme indicates we should be replacing a key for release. I believe it also includes the private key in the comments. This is on crypto.cpp:1083
```
// FIXME: replace this for release
// pub aa558eb043105536d72a433d8fa121797f134805c526727c43f57cefdaec289b  priv aa55aa55aa55aa55aa55aa55aa55aac97034aa55aa55aa55aa55aa55aa55aa55
uchar rootcert[] = { 0xaa, 0x55, 0x8e, 0xb0, 0x43, 0x10, 0x55, 0x36, 0xd7, 0x2a, 0x43, 0x3d, 0x8f, 0xa1, 0x21, 0x79,
                     0x7f, 0x13, 0x48, 0x05, 0xc5, 0x26, 0x72, 0x7c, 0x43, 0xf5, 0x7c, 0xef, 0xda, 0xec, 0x28, 0x9b };
```

**Comment by drian0** [comment]
Thank you for this report, I will look into it.

**Comment by drian0** [comment]
crypto.cpp:913
I wrapped this code with a release preproc directive so that it remains testable before a release build.

crypto.cpp:1083
It appears that this code is currently not in actual use because no certificate files reside in the given configuration directory at the moment - and so we should keep it. Correct me if I'm wrong.
