### ISSUE TITLE
[release_1.3] there should be no sound when respawning

### ISSUE THREAD

**Issue by drian0** [assaultcube/AC#257]
Original report from BrutalSystem:
`ok, I suspected this bug, but I wasn't sure, but today I called a friend to test things with me, so when someone respawn I hear the sound of the gun being selected (I'm not sure if this is the sound), so I know the enemy's position as soon as he respawn`

**Comment by drian0** [comment]
This has been corrected. BrutalSystem, could you pleas re-test? Thank you!

**Comment by BrutalSystem** [comment]
> This has been corrected. BrutalSystem, could you pleas re-test? Thank you!

has been fixed, but I noticed that I don’t hear when someone changes weapons, I don’t know if it’s this fix that broke it.
