### ISSUE TITLE
[release_1.3_alpha1] spectatemode 5 be disabled for active players (metagame)

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#259]
player Xemi requested that spectatemode 5 be disabled for active players.

reason: it is used a lot when dying, to see the enemy's position, looking where he is going, some even delay the respawn waiting for the enemy to enter the base and then respawn and kill him.

**Comment by drian0** [comment]
There are currently different ideas under what circumstances spectatemode 5 should be allowed. Can we apply the same constraints as for spectatemode 6? 

Entering spectatemode 6 is prevented if at least one of the following conditions apply:
- mastermode is not private or match
- player is dead
- player is in spect team --> /benchme

Thank you for clarification.

**Comment by BrutalSystem** [comment]
> There are currently different ideas under what circumstances spectatemode 5 should be allowed. Can we apply the same constraints as for spectatemode 6?
> 
> Entering spectatemode 6 is prevented if at least one of the following conditions apply:
> 
> * mastermode is not private or match
> * player is dead
> * player is in spect team --> /benchme
> 
> Thank you for clarification.

spectator mode 5 should only work for spectators if the server is private or match, and when you die your vision should go to your teammate's screen, but we have a problem here, what should happen when everyone dies?

I have two ideas:

1) your vision will return to the point where your body died and you will not be able to move your vision to look back.

2) your screen will become bloody and red (obscuring your view)

**Comment by drian0** [comment]
> and when you die your vision should go to your teammate's screen, but we have a problem here, what should happen when everyone dies?

Is my understanding correct that this requirement/idea is not linked to spectatemode 5? Could you please move this to another change request? Thanks.

**Comment by drian0** [comment]
Entering **spectatemode 5 and 6** is now prevented if at least one of the following conditions apply:

- mastermode is not private or match
- player is dead
- player is in spect team --> /benchme

Thank you in advance for re-testing this.

**Comment by BrutalSystem** [comment]
@drian0 currently spectator mode 5 is not working for spectators when server is (open).

**Comment by drian0** [comment]
Maybe related to #344

**Comment by flowtron** [comment]
I've changed the availability of the 'overview' spectator mode. But that has shown me a new issue (issue #395 ): the overview sometimes renders a side view, not an eagle's view.
