### ISSUE TITLE
[release_1.3_alpha1] unassigned texture path

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#264]
![20210422_01 01 45_dev_apollo_abbey_TDM](https://user-images.githubusercontent.com/7694535/115640743-0bded080-a2ee-11eb-8c9b-1768858b8794.jpg)
![20210422_01 08 12_dev_apollo_abbey_TDM](https://user-images.githubusercontent.com/7694535/115640758-11d4b180-a2ee-11eb-8c3e-6bbb59e2d49f.jpg)

when texture path appears as unassigned, it is not possible to add a new path using texture path, you can add texture path, but change does not occur

**Comment by drian0** [comment]
Does this problem happen 
- with newly created maps or 
- or only with existing/migrated maps?

My basic assumption is that newly created maps do not run into this issue.

Could you please try this workaround?

```
/edittextureslot ID SCALE PATH
// in your case: 
/edittextureslot 60 0 "yourpath"
```

Thanks for reporting.

**Comment by BrutalSystem** [comment]
> Does this problem happen
> 
> * with newly created maps or
> * or only with existing/migrated maps?
> 
> My basic assumption is that newly created maps do not run into this issue.
> 
> Could you please try this workaround?
> 
> ```
> /edittextureslot ID SCALE PATH
> // in your case: 
> /edittextureslot 60 0 "yourpath"
> ```
> 
> Thanks for reporting.

usually with existing / migrated maps as this is a failure of the authors to change the .cfg file and forget something, but this can happen in the newly created maps if the author chooses to save the map using / savemap9 and change the .cfg files manually.

the solution did not work.
how I am getting around this situation, I add new texture until the new texture takes the place of the current slot that is failing

**Comment by BrutalSystem** [comment]
I will not go into the comments of others because I use Google translator and when I make huge text it is easy to go wrong.

I like "lightscale" because the lighting of the AC is a horrible fault of the authors of the maps, this must be maintained if we do not find a solution.
but players shouldn't have the power to choose the light scale, "lightscale 2" is good enough for me.

gamma is horrible, it really is not a solution.

modifying the lighting of the maps is the best option but we will stop at the license of the maps again.

**Comment by drian0** [comment]
The solution worked for me. Could you please ping me in Discord so that we can troubleshoot this together?

**Comment by drian0** [comment]
I was able to reproduce this problem now with the map ac_apollo_abbey.

The texture slot 60 is not defined however it is referenced by geometry. The last defined texture slot is 59. Please simply add another texture definition:

`/texture 0 "asdf.png"`

I hope this works for you.

Ideally there would be a GUI for this. If you'd like you can create a feature request for this.
