### ISSUE TITLE
[release_1.3_alpha1] can not change resolution in fullscreen mode

### ISSUE THREAD

**Issue by drian0** [assaultcube/AC#268]
Originally reported by Koptan.
```

but i cant change resolution in to any same 1920 1080
i can only change it in window mode not fullscreen
```

**Comment by BrutalSystem** [comment]
![20210422_20 27 32_ac_rampart_TDM](https://user-images.githubusercontent.com/7694535/115780943-28cbe000-a390-11eb-96cc-e17f84be81df.jpg)
fullscreen is always using desktop resolution

**Comment by drian0** [comment]
Closing this for now. By now **two** people have not seen that option and complained that they can not change resolution. We may need to improve UX if more people fail to recognize this option.
