### ISSUE TITLE
[release_1.3_alpha1] "score" is not working

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#269]
![20210422_20 56 38_ac_nocturne_CTF](https://user-images.githubusercontent.com/7694535/115800876-d1d70280-a3b1-11eb-9e94-5f58a9f6a9f0.jpg)

**Comment by drian0** [comment]
As far as I can tell the scoring system has been removed meaning the empty "score" column is a left-over.

Please see details @ https://github.com/assaultcube/AC/commit/1fe478aae44fd1fd0a8e584f600ac3e92fc0d7ee#

**Comment by drian0** [comment]
I cleaned up the leftovers. The column is gone now. Thank you for reporting this.
