### ISSUE TITLE
[release_1.3_alpha1] Player rag-doll fails to properly align to floor when player is killed by nade

### ISSUE THREAD

**Issue by AC-Panda** [assaultcube/AC#270]
![20210422_20 16 36_ac_desert_TDM](https://user-images.githubusercontent.com/69180012/115925279-bca3b780-a435-11eb-95ad-4c9251ccfce8.jpg)

**Comment by drian0** [comment]
Does this happen all the time or only in certain places/maps?

**Comment by drian0** [comment]
I could not reproduce this with a nade unfortunately.

**Comment by AC-Panda** [comment]
I haven't had enough game-play time AC 1.3x enough to properly judge if it was a map issue. I wonder is it a gibnum collision issue.

**Comment by drian0** [comment]
I am closing this for now. Please re-open if you can reproduce this.
