### ISSUE TITLE
[release_1.3_alpha1] HUD gun-sway fails to pause at intermission

### ISSUE THREAD

**Issue by rpaladin** [assaultcube/AC#271]
Current HUD item's sway motion fails to stop at the end of the game round.

**Comment by drian0** [comment]
Thank you very much. I was able to reproduce this issue.

**Comment by drian0** [comment]
Thank you. This has been resolved.

**Comment by drian0** [comment]
This issue happens again in BETA3.

**Comment by RandomPandaStudios** [comment]
I wonder if something simple like this would work even:
```
start_intermission = [ nosway 1 ]
```

**Comment by flowtron** [comment]
Since we now move to the VANTAGE POINT of the map for intermission there's also no hudgun being rendered. Closing.
