### ISSUE TITLE
Is there gonna be any change in Server Tick rate for 1.3?

### ISSUE THREAD

**Issue by Punjara** [assaultcube/AC#273]
I don't know what is current server tick rate for 1.2. But I assume it's not 60 Hz ? So Dying behind cover, Hit register, movements and all gonna be the same or any plans for introducing high tick rate servers..Even Battlefield has 60 Hz servers and assaultcube is much more fast paced than that.

**Comment by drian0** [comment]
AC uses a fat client architecture so I think your idea is not applicable.
