### ISSUE TITLE
[release_1.3_alpha1] Sniper scope sensitivity inverted ?

### ISSUE THREAD

**Issue by Punjara** [assaultcube/AC#274]
Sniper-scope sensitivity scale value is greyed out when selecting manual. Shouldn't it be the other way around ? Automatic should grey out the scale value ?
![20210424_18 17 12_ac_nocturne_TDM](https://user-images.githubusercontent.com/83135497/115968891-95dda200-a557-11eb-8ca5-4710f16c3fd4.jpg)

**Comment by drian0** [comment]
Thank you very much, we will look into this.

**Comment by drian0** [comment]
This has been fixed. Thank you very much.
