### ISSUE TITLE
Character Model Location..

### ISSUE THREAD

**Issue by Punjara** [assaultcube/AC#276]
Here is what character model on Skin selection menu...Character model is somewhat behind the gun. Is it possible to move its location so that it is visible completely.
![20210425_13 29 58_ac_elevation_TDM](https://user-images.githubusercontent.com/83135497/116002117-cdab1f00-a615-11eb-82a9-8c109ba8ded6.jpg)

**Comment by cf-1984** [comment]
Shouldn't the model be rendered on the GUI layer, like the menu, therefore always on top of the HUD gun?

Would the positioning then be OK?

**Comment by Punjara** [comment]
Yup that will be consistent, but is there a way to implement 'Blur' on viewport, or is it baked into the engine ? You can do that also for the focus on the Menu and Model and blur the rest of the things. IDK.

**Comment by drian0** [comment]
Thank you very much. This has been resolved.
