### ISSUE TITLE
[release_1.3_alpha1] Bind to mousekeys >5 not working

### ISSUE THREAD

**Issue by cf-1984** [assaultcube/AC#278]
Can not bind to mouse keys other than key 1-5. Tried to bind to mouse6 (close thumb key on Razer Deathadder), but it won't perform the bound action. No error message or other feedback given, neither when setting up the bind command, nor when pressing the button.

**Comment by drian0** [comment]
Thanks for reporting this. Did this work properly in AC v1.2 ?

**Comment by AC-Gazda** [comment]
I have similar issue on my CoolerMaster Mastermouse Pro L. Mouse is symetrical and features 2 "Thumb buttons" on each side. Left pair can be bound to "mouse8" and "mouse9", however right pair does not work with any number up to 16.

In 1.2 left pair was named mouse6 and mouse7. Mouse8 did not do anything,  and it was also maximum allowed mouse key number.

**Comment by drian0** [comment]
@AC-Gazda
Do I understand you correctly in that you managed to get your mouse keys bound properly with v1.3? Thanks for your feedback in advance.

**Comment by AC-Gazda** [comment]
Yes, only the numbers were different. I did not test the right side anymore because the keys are programmable.
On the left keys are set to "Browser Back" and "Broswer Forward".

**Comment by drian0** [comment]
@cf-1984 
Could you please check if you can get your mouse key bindings to work with the solution mentioned by AC-Gazda ?

**Comment by cf-1984** [comment]
Thanks AC-Gazda!

Indeed, what used to be mouse6/7 in v1.2 now is mouse8/9 and can be bound just as expected. This solves the issue, but it isn't exactly user friendly to figure this out by trial and error.

**Comment by drian0** [comment]
Thank you very much for confirming this. 

If you find a good place to document this hint (in the .cfg maybe?) then feel free to send a pull request.
