### ISSUE TITLE
[release_1.3_alpha1] Some team voicecoms are public

### ISSUE THREAD

**Issue by elmillion** [assaultcube/AC#282]
Some voicecom commands that should only be heard in team can be heard by everyone.

v23 : Come on, move!
v34 : Enemy down
v42 : Sorry

If that's normal maybe they should be moved to "Public Talk"

**Comment by drian0** [comment]
Thanks for reporting this.

**Comment by drian0** [comment]
I am adding voicecom specialist flowtron to the loop.

**Comment by drian0** [comment]
Flow fixed this with commit 3d0972a
