### ISSUE TITLE
[release_1.3_alpha2] Strange FOV while spectating

### ISSUE THREAD

**Issue by elmillion** [assaultcube/AC#283]
That happened only when spectating this person. All people on the server could see his fov like this : 

![image](https://user-images.githubusercontent.com/83298586/116276351-b6d70a80-a784-11eb-8e40-ae776fe033fe.png)

While he was playing with fov 90, that should look like this 

![image](https://user-images.githubusercontent.com/83298586/116276436-d110e880-a784-11eb-8cbb-ea6110164eee.png)

But I think we shouldn't even see his fov, but our `spectfov`. The first screenshot is taken with `spectfov 120`, so it should have looked like this 

![image](https://user-images.githubusercontent.com/83298586/116276873-395fca00-a785-11eb-9a9e-c53f8fa01613.png)

**Comment by elmillion** [comment]
Not able to reproduce it tonight.

**Comment by drian0** [comment]
Ok, please let me know once you manage to reproduce it again. Thank you!

**Comment by drian0** [comment]
I am closing this for now. Please re-open should you manage to reproduce this. If you manage to reproduce this then maybe check with other players also. Thank you very much.

**Comment by BrutalSystem** [comment]
how to reproduce: die with scope open and switch to another weapon

**Comment by elmillion** [comment]
I confirm, I can reproduce using @BrutalSystem method : 
Player 1: 
 - Die while scoping with sniper
 - Change weapon to something else than sniper
Player 2:
 - Spectate Player 1

@drian0
