### ISSUE TITLE
[release_1.3_alpha1] Toggle for /pointatent missing in editing menu

### ISSUE THREAD

**Issue by cf-1984** [assaultcube/AC#286]
In edit mode entities can now be selected by pointing at them. This requires pointatent = 1, current default value is 0, which is ok. However, there should be a corresponding menu entry in the editing menu within settings for toggling this setting on/off for easy access and as a hint this feature even exists.

**Comment by Felix-The-Ghost** [comment]
How does it work with entities in the same spot?

I bet it would be easy to adjust entities sparkle height when created to automatically avoid overlapping sparkles

How accurate do you have to be when "pointing" to an entity to select?

Sorry I'm not familiar with this feature.

Does the entity text info at the bottom change to reflect selected (targeted better term?) entities?

**Comment by cf-1984** [comment]
When there are two or more entities in the same spot it will select the one, which happens to be closer to the selection. Just like it works now with mere 'approximation selection'. However, you already (v1.2) can change the sparkle height ingame, after an entity is placed. When it is selected look straight down on it, or straight up from it, keep pressing M and scroll the mouse wheel to move the sparkle up/down. Mapmodels and entities can be moved around in 3D this may, when looking horizontally, btw. In v1.3 the way the mouse scroll works has been changed, so scrolling up will now always push the object away and scrolling down pulling it closer. In v1.2 it depends on the axes and orientations, so depending on that the scrolling direction will change.

The idea of fixed sparkle heights (or user configured heights) has floated around in the past, but I think got dismissed due to the possibilities explained above. At least I don't know of any such feature in v1.3. Maybe something to look into in the future?

You don't have to be that accurate, but you have to point at the sparkle, not the entity/mapmodel.

Yes, the targeted sparkle will be highlighted (blue color) and the entity info panels (lower left and right) will show the info of the targeted entity. The selection can be pinned (middle mouse button), which will also be highlighted (word 'pinned' in red) as well. In order to un-pin an entity you simply press middle mouse button again.

In my opinion this works pretty well the way it is now and will certainly be my future workflow when it comes to map editing. I encourage you trying it out yourself and provide feedback if you see areas for improvement.

**Comment by Felix-The-Ghost** [comment]
I'm aware of the entity scrolling. I was suggesting that, since unless it was changed the height of the sparkle is the same as the player when it is created, it could iterate through them on creation (and scrolling probably) to avoid having two entities in the same exact spot.

IMO "selected entity" sounds more accurate than "pinned" entity UNLESS I misunderstand what a pinned entity is.

In my mapping client there is also a bind to select an entity but there is no entity targeting mechanic so the closest entity is used (until selected)

![mapmodelselection](https://user-images.githubusercontent.com/7077936/116603144-359d8600-a8f2-11eb-9d9e-e6dfaeadec96.gif)

**Comment by cf-1984** [comment]
I believe 'selected entity' is already the term for closest entity, so someone came up with another term for that particular feature. The logic behind this wording probably is rather 'pinned selection' than 'pinned entity'. Does this then sound more accurate?

**Comment by BrutalSystem** [comment]
> In edit mode entities can now be selected by pointing at them. This requires pointatent = 1, current default value is 0, which is ok. However, there should be a corresponding menu entry in the editing menu within settings for toggling this setting on/off for easy access and as a hint this feature even exists.

check editting keys menu

**Comment by Felix-The-Ghost** [comment]
> I believe 'selected entity' is already the term for closest entity, so someone came up with another term for that particular feature. The logic behind this wording probably is rather 'pinned selection' than 'pinned entity'. Does this sound more accurate?

Oh, I evidently forgot that was how it appears currently.
In my mapping client the closest entities are displayed as "closest entity" and the selected entity is the "selected entity"

Check out that gif I posted to see it changes from "closest entity" to "selected entity" IMO this verbage has the least ambiguity. targeted entity (new to me) nearest entity, and selected entity are what I think it should say

"Pinned entities" reads to me as "bookmarked" entities which could be interesting in itself but has a different meaning than intended

**Comment by drian0** [comment]
This has been resolved. Thank you.
