### ISSUE TITLE
[release_1.3_alpha1] unclutter initial setup screen

### ISSUE THREAD

**Issue by drian0** [assaultcube/AC#292]
The initial setup screen has currently too many settings. This became clear because players overlook the option "Fullscreen option is always using desktop resolution". Only the most important settings should be visible on that screen. The target audience we optimize this for should be **new players** because existing AC players have their specific cfg's/scripts/binds anyway.

See /showmenu "QUICK setup"

Suggestion:
![image](https://user-images.githubusercontent.com/78469463/116780517-a7eea180-aa7d-11eb-9b98-67571c3e4ac5.png)

Rationale:
- Name, resolution, fullscreen are the most important settings (plus "brightness" --> gamma)
- You can not return to the setup screen once you close it (!) Therefore it does not make sense to have sensitivity there because for *new* players sensitivity is trial and error. Set it, try it out, adjust it, try it out ... 
- Move the other settings to the Settings menu (High-res skins, sens, reduced violence mode, graphics detail, sound detail, fov)

Any thoughts on that?

**Comment by BrutalSystem** [comment]
> Any thoughts on that?

vsync
turn off music
selection weapon

**Comment by drian0** [comment]
@BrutalSystem that's too much material on the screen in my opinion.

**Comment by drian0** [comment]
This issue has been resolved.
