### ISSUE TITLE
Mapmodel preview works a bit strange

### ISSUE THREAD

**Issue by NadalB** [assaultcube/AC#293]
If u look other direction the previewed model rotate too. 

[https://imgur.com/OHOMO0j](url)
[https://imgur.com/ubONSEy](url)
[https://imgur.com/13crq9R](url)

**Comment by BrutalSystem** [comment]
> If u look other direction the previewed model rotate too.
> 
> [https://imgur.com/OHOMO0j](url)
> [https://imgur.com/ubONSEy](url)
> [https://imgur.com/13crq9R](url)

I think it was designed to be like this, it works like a rotation

**Comment by drian0** [comment]
I think this has been done on purpose so that you see the object from all angles. I am closing this. Nevertheless thank you for testing and reporting.
