### ISSUE TITLE
reset the selection of cubes if you select any part already selected using the mouse

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#299]
type: / resetselections
avoiding accidentally changing any selected forgotten part.
I know there is this command for this, but I think it should be added to the mouse function as well, because I find it more intuitive for new people is this command for this, but I think it should be added to the mouse function as well, because I find it more intuitive

**Comment by Felix-The-Ghost** [comment]
/resetselections is undocumented what exactly does it do?

>  added to the mouse function as well

What do you mean? In the editing menu or a default bind?

**Comment by Felix-The-Ghost** [comment]
Just checked from code snippets: looks like it removes all selections like the pretty universally  standard term "deselect" right?

Well probably don't rename it since some scripts may exist already but perhaps a new alias should be added: /deselect that is just an alias/nickname for /resetselections

**Comment by BrutalSystem** [comment]
> /resetselections is undocumented what exactly does it do?
> 
> > added to the mouse function as well
> 
> What do you mean? In the editing menu or a default bind?

can be done with scripting, but I thought about hardcord anyway

**Comment by Felix-The-Ghost** [comment]
Can you please be explicit what exactly you want to happen

**Comment by BrutalSystem** [comment]
> Can you please be explicit what exactly you want to happen

[like in the video, I selected the cube, and I selected it again.
then should deselect](https://drive.google.com/file/d/14zNxY_FdjGzJpkT6Rmt7fGRmF788vo82/view?usp=sharing)

**Comment by Felix-The-Ghost** [comment]
I think I understand. you would like to deselect the selection by clicking it? I think actually that could be programmed but would have to decide how exactly to design it so it's obvious you can do that (was thinking maybe the corner cube of the selection could have an X rendered in it similar to the X button when closing windows on a computer

**Comment by BrutalSystem** [comment]
> I think I understand. you would like to deselect the selection by clicking it? 

exactly

**Comment by Felix-The-Ghost** [comment]
I'd actually love to work on this. Thought about it a little bit from my tinkering in some related code and I'm condiment I can do this.

If no one else implements something similar I may in the future come back to this.

**Comment by Felix-The-Ghost** [comment]
I'd actually love to work on this. Thought about it a little bit from my tinkering in some related code and I'm confident I can do this.

If no one else implements something similar I may in the future come back to this.

**Comment by BrutalSystem** [comment]
[stef said the reason for not having deslect the selection by clicking is because you can select several areas and then it will happen :D ](https://drive.google.com/file/d/1Z4uGr270-2oyhyXbt-fhkVc3zbfy2VVp/view?usp=sharing)

**Comment by BrutalSystem** [comment]
I'm closing this issue because I now know why this doesn't need to be implemented.

**Comment by Felix-The-Ghost** [comment]
I don't understand either of your last two comments

**Comment by BrutalSystem** [comment]
> I don't understand either of your last two comments

the reason that my request should not be implemented is because of that.
![20210620_21 22 18_newmap_TDM](https://user-images.githubusercontent.com/7694535/122688794-c0b14300-d1f4-11eb-8620-0f1345fbca92.jpg)

you can select multiple times the same selection and then use ctrl(editmeta)+ scroll up and easily turn a selection into this.
![20210620_21 22 27_newmap_TDM](https://user-images.githubusercontent.com/7694535/122688852-053cde80-d1f5-11eb-87b0-5f8be103377e.jpg)

**Comment by Felix-The-Ghost** [comment]
I'm just more confused now.

**Comment by BrutalSystem** [comment]
> I'm just more confused now.

It's because if this feature I asked to be added will kill other feature that was added for 1.3

anyway, i know you are currently computerless and access using your mobile phone, so i suggest you to enter the assaultcube Discord by downloading the discord app or simply logging into your mobile browser to remove any queries you may have.

**Comment by Felix-The-Ghost** [comment]
What is your native language, friend?

**Comment by BrutalSystem** [comment]
> What is your native language, friend?

Portuguese-BR, I use a translator to communicate, I know it's not perfect, but I try my best so that nothing too weird comes out.
