### ISSUE TITLE
Non-player initiated team changing should only occur between death and respawn

### ISSUE THREAD

**Issue by RandumKiwi** [assaultcube/AC#3]
If you're on a server, and you get forced to the other team, and you have JUST thrown a grenade, if the grenade kills someone, the system reports it as a TK, even though you were on the opposite team when you threw the grenade.

This is a complicated issue - rather than fixing the code to remember the team when throwing, we'd need to fix the whole teamchange procedure. It should only change your team between death and respawn. It should also be shown more prominently.

**Comment by drian0** [comment]
The approach proposed by @lucasgautheron would work. However I believe that the additional complexity that is added to the codebase is not justified by the value of this functionality.
