### ISSUE TITLE
Win 32 Exception: 0x0000005 

### ISSUE THREAD

**Issue by Naqikhan** [assaultcube/AC#308]
Game won't launch and will give me this error.
![Capture](https://user-images.githubusercontent.com/44385168/117272619-fc4ca500-ae20-11eb-810b-950300045299.PNG)

**Comment by drian0** [comment]
Were you able to resolve this issue? I am asking because you reported other issues so I assume you managed to launch the game.

**Comment by Naqikhan** [comment]
i had to reinstall both cube and redownload the Alpha build. It did start working after that

**Comment by drian0** [comment]
Ok, let us reopen this issue if other people report the same problem. Thank you.

**Comment by MusawarShahSyed6969** [comment]
Same Issue

**Comment by adeliktas** [comment]
This is a common issue with newer amd gpu drivers. Install the stable version 22.5.1 driver to fix your issue.

**Comment by Kunal1320** [comment]
Facing same problem

**Comment by ac-jamz** [comment]
@Kunal1320 If you have AMD graphics, try this: https://github.com/assaultcube/AC/issues/465#issuecomment-1461365722

**Comment by Virat-Gupta** [comment]
I faced the same problem, I fixed by **stopping screen projection** and using only laptop screen.
