### ISSUE TITLE
[release_1.3_alpha1] map sent to server

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#320]
when sending map to servers, the .cfg file of map is created, even if map does not contain

**Comment by flowtron** [comment]
that bit is easily fixed; but there's more going on here - I see a number of _wrong_ error messages regarding "upload failed" (client) and "no incoming?" (server) .. but the file was uploaded properly. I will investigate this tomorrow.

**Comment by drian0** [comment]
Related: 
https://github.com/assaultcube/AC/issues/341
https://github.com/assaultcube/AC/issues/320
https://github.com/assaultcube/AC/issues/297
