### ISSUE TITLE
[release_1.3_alpha2] coopedit mode is missing from the UI

### ISSUE THREAD

**Issue by drian0** [assaultcube/AC#340]
Coop-edit should be accessible in the UI so that people learn about it. Please see the screenshot below.

Coop-edit may not be supported under certain circumstances for examples if servers disabled it. In this case instead of "Cooperative Editing" the menu item  should read "Cooperative Editing [disabled]" and clicking it should have no effect.

![image](https://user-images.githubusercontent.com/78469463/117830070-970b1080-b273-11eb-9d4c-237a77b9c1b8.png)

**Comment by AC-Gazda** [comment]
By ability of servers to disable it, are we talking about a new switch in servercmdline.txt or an existing one `-Pe`?

**Comment by AC-Gazda** [comment]
A simple solution I see would be parsing serverdescription for a keyword such as `[COOP]` or `[COOP ENABLED]`. Is that an acceptable solution?
Of course that would only a have visual effect on the menu. Permissions to actually vote coop would remain unchanged; `-Pe` or admin. Should those be reviewed too?

**Comment by zeSKB** [comment]
> A simple solution I see would be parsing serverdescription for a keyword such as [COOP] or [COOP ENABLED]. Is that an acceptable solution?

Absolutely not. If there's no cubescript var, expose it to cubescript. If client is not aware of server capability, this will require protocol change, which should probably just be moved to backlog for a future release.

**Comment by flowtron** [comment]
The -P and -M switches have a wide range of possible permissions for every running server. Voting for COOP can be allowed or restricted; creating and updating can be done by anybody or just those that have admin permissions on the server.

Finding out what the settings of a specific server are will require a change of protocol - a whole new EXTPING_PERMISSIONS. 

What could be done _now_  is to always show the option and show a failure message if the server denies access - that is _not_ better UX, like what drian wants, that will require EXTPING_PERMISSIONS.

**Comment by drian0** [comment]
I was not aware that a protocol change is required. In this case let go for the simplified approach that flowtron suggested:

`What could be done now is to always show the option and show a failure message if the server denies access`
