### ISSUE TITLE
[release_1.3_beta1] Improve server private key documentation

### ISSUE THREAD

**Issue by RonaldReagan** [assaultcube/AC#353]
Currently server owners who want their servers need to setup a server private key. Without reading through the source code it is difficult to know why a server is LAN only. Current problems:

- When missing -Y parameter server starts in LAN only mode with no warning as to why
- No docs on -Y
- No indication of how to generate it

Possible solutions:

- Use new server parameters feature. When it is blank, autogenerate the key and save it in the parameters file.
- Make it not required
- Provide better documentation and keep current mechanism
- Read private key in from file. -Y can be changed to specify file location.

**Comment by ac-stef** [comment]
Given the fact, that the new auth system implementation is, at best, about 50% finished, another "possible solution" would be to

- figure out what's missing and finish implementing it.

Of course "-Y" was a quick fix for testing purposes, which is why it was never documented. To require a secret to be passed via command line for anything other than testing purposes would be quite stupid, right?

**Comment by RonaldReagan** [comment]
> Given the fact, that the new auth system implementation is, at best, about 50% finished, another "possible solution" would be to
> 
> * figure out what's missing and finish implementing it.


Agreed. At this point we are pushing for a release and I'm interested in utilizing our dev time to get us into a releasable state. That being said, I'll never say no to someone wanting to contribute code to the project if a specific feature inspires them. We can always iterate and improve in future releases if needed.

Do you know what all needs to be implemented? I'm not clear on the vision for the feature and what needs to be done.

**Comment by ac-stef** [comment]
If that is the situation, then you should revert to 1.2. Backport some fixes and release.

**Comment by flowtron** [comment]
There are probably a number of related/follow-up issues but commit a29ffeed - along with the update to doc/server.html on the website repository - should get us release ready.
