### ISSUE TITLE
Server log game status needs "score" column removing or sanitising.

### ISSUE THREAD

**Issue by ac-jamz** [assaultcube/AC#355]
![image](https://user-images.githubusercontent.com/5977845/119315138-7082a780-bc6d-11eb-8d15-4824f07acf84.png)

**Comment by flowtron** [comment]
fixed in [commit 9ae4213a](https://github.com/assaultcube/AC/commit/9ae4213a9571d55e453b55147177bd1af3d3f459)

**Comment by drian0** [comment]
@flowtron 
Could you remove *state.points* altogether from the struct? This should not be used/referenced anymore I guess.

**Comment by flowtron** [comment]
This is rather involved, there is a ton of stuff being done; e.g. regarding balancing teams that relies directly or indirectly on that value. We should chat about the details/implications before I commit something that breaks the game.

**Comment by drian0** [comment]
Related to https://github.com/assaultcube/AC/issues/269
