### ISSUE TITLE
Suddenly there is no sound

### ISSUE THREAD

**Issue by Sergio6936** [assaultcube/AC#357]
I was playing CTF and suddenly the sound of the game was gone. I had to restart the game to get sound again. It has happened to me a few times for a long time, I would not know very well how to reproduce the bug since I do not know what can cause it. Could you tell me some possible solutions if you know? Thank you.

**Comment by AC-Panda** [comment]
Known bug in 1.2x.

# Proof / Solutions / Instructions
https://wiki.cubers.net/action/view/FAQ#The_sound_keeps_disappearing_on_Windows

**Comment by AC-Panda** [comment]
@drian0 this bug is already fixed, did you perhaps forget?

# Link: https://github.com/assaultcube/AC/issues/226

**Comment by drian0** [comment]
Thank you.
