### ISSUE TITLE
[release_1.3_beta1] bug with copyent/pointent

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#379]
when **pointent** is enabled **copyent** should only work when you have an **entity selected**.

currently **copyent** is copying nothing while you are looking at the wall, this is generating several empty copy entries in the **paste entity menu**.

**Comment by BrutalSystem** [comment]
It is likely that hide entity will affect copyent too.

**Comment by flowtron** [comment]
commit f84001ff fixes this; we just needed to make copyent ignore the -1 index (meaning: no entity found), hideentmask was already being observed.
