### ISSUE TITLE
[release_1.3_beta1]using cleanshot in edit mode causes this issue.

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#381]
> unknown command: seteditshow
(from console or builtin [PROMPT])
exec nesting level: 4
 seteditshow 0 

>unknown command: seteditshow
(from console or builtin [CFG])
exec nesting level: 3
seteditshow

**Comment by flowtron** [comment]
that script was there before **edithideentmask**, but a nearly perfect version was lying around in opt/compatibility.cfg - fixed in aad46263
