### ISSUE TITLE
[release_1.3] grenade physics is broken

### ISSUE THREAD

**Issue by drian0** [assaultcube/AC#388]
Original bugreport: "The grenade bug was not fixed, and flowtron created another grenade bug that was even more problematic."

Steps to reproduce:
...

Expected:
...

Actual:
...

**Comment by BrutalSystem** [comment]
Bug occurred because I was using v1.3 at the current stage while the server is in a beta version of 1.3, I tested it on a local server with all updates and it didn't happen, I'm closed this issue.
