### ISSUE TITLE
[release_1.3_beta1] spectate:overview sometimes side view

### ISSUE THREAD

**Issue by flowtron** [assaultcube/AC#395]
I came across this when working on issue #259 : the eagle-eye view (like radar, a top-down view) is sometimes a view from the side instead. It may be related to the map in question, ac_aqueous showed this twice in my memory; but no research has been done here yet.

**Comment by BrutalSystem** [comment]
> I came across this when working on issue #259 : the eagle-eye view (like radar, a top-down view) is sometimes a view from the side instead. It may be related to the map in question, ac_aqueous showed this twice in my memory; but no research has been done here yet.

this happens while you are in `specatatemode 6` and `changes map`, but it doesn't happen on all maps, just some. no need to thank :D

**Comment by flowtron** [comment]
Yeah. That is what I found too. I will look into the code for any obvious mistakes, but I will probably try need to find a pattern: some way to reliably reproduce the bug. That should help pinpoint the place in the code where the non obvious mistake is hiding. But who knows, maybe it's a simple and obvious mistake :-)
