### ISSUE TITLE
unresolved problems occurred during load_world(), warning: 0x1

### ISSUE THREAD

**Issue by xdanielx52** [assaultcube/AC#402]
As the title says, i always get the error:
unresolved problems occurred during load_world(), warning: 0x1
when loading a few maps. 
a few props, that should be at a different height are somehow placed lower than they should. funny enough, the collision is also lowered and people are thinking, that i'm hacking when running on the bugged props.
i am compiling it with msys2 32-bit mingw-make.exe 
here are 2 screenshots of said issue:
![ac_load_world_problem1](https://user-images.githubusercontent.com/92151999/136527469-aa988616-9988-436d-87c5-b9a123f5688d.png)
![ac_load_world_problem2](https://user-images.githubusercontent.com/92151999/136527501-298ec2ab-9604-432a-a84d-a317d59bcf63.png)

**Comment by ac-stef** [comment]
Did you read the other messages?
