### ISSUE TITLE
[release_1.3_beta3] Post-installation release notes for 1.3 missing

### ISSUE THREAD

**Issue by drian0** [assaultcube/AC#403]
On windows the following page is automatically opened in a browser after installing AC:
_https://assault.cubers.net/releasenotes/v1.3/_

Likewise after uninstallation the following page is opened:
_https://assault.cubers.net/uninstallnotes/v1.3/_

These two pages are missing and need to be created.

**Comment by flowtron** [comment]
repository updated

**Comment by drian0** [comment]
Thank you.
