### ISSUE TITLE
Build older version

### ISSUE THREAD

**Issue by symbios24** [assaultcube/AC#417]
Hello there
What if i want to build the older version 1.2.0.2
Now that AC is updated to 1.3 version
If i clone the repo like this: https://github.com/assaultcube/AC.git
What version it will clone ??
If it will clone the 1.3 how can i clone the 1.2?
Thanks

**Comment by pseiler** [comment]
```git clone https://github.com/assaultcube/AC.git
git checkout 12.0.2```
Then follow the build instructions. You can also create a local branch for it.

Or just download it from here.
https://github.com/assaultcube/AC/releases/tag/v1.2.0.2

**Comment by aurhat** [comment]
It isn't good idea - https://github.com/assaultcube/AC/releases/tag/v1.2.0.2 -> "Therefore the [libcurl4_1202_hotfix](https://github.com/assaultcube/AC/tree/libcurl4_1202_hotfix) branch **should** be used by packagers for the newest Linux systems/distributions"

**Comment by symbios24** [comment]
Thanks,so what method is correct to use to clone the 1.2.0.2 ?
