### ISSUE TITLE
Score disappeared from scoretable in 1.3?

### ISSUE THREAD

**Issue by AlmuHS** [assaultcube/AC#418]
I've just test AC 1.3, but I notice that the "score" column (which exists in 1.2) has disappeared in 1.3.

Scoretable in AC 1.2

![Scoretable in AC 1.2](https://user-images.githubusercontent.com/15078104/145477314-2eca090f-103e-4037-88c5-b0c23edf2112.png)

Scoretable in AC 1.3
![Scoretable in AC 1.3](https://user-images.githubusercontent.com/15078104/145477353-3af92cc7-4dfc-4c63-960d-e9e449efdce2.png)

Are there any way to recover this column?

**Comment by auermich93** [comment]
Would be nice to re-include this feature. In the code, the `SV_POINTS` message is still present.

**Comment by drian0** [comment]
As far as I can tell the scoring system has been removed in 2017 on purpose.
details @ 1fe478a
