### ISSUE TITLE
Respawning in bot modes doesn't reset camera

### ISSUE THREAD

**Issue by Felix-The-Ghost** [assaultcube/AC#62]
IE whatever position the camera was in when you clicked to respawn is the camera position when you spawn. So you can die, look straight up, spawn and you'll be looking straight up. Look down before respawning and you'll spawn looking down. This is only in bot modes.

**Comment by Felix-The-Ghost** [comment]
Is this fixed in the next version?

**Comment by aurhat** [comment]
No, bot modes have very low priority. In 1.0.4 was ok, so bisect should show, which commit broke that. Do you want maybe to use bisect and find this commit yourself?

**Comment by aurhat** [comment]
Thanks, fixed. :)
