### ISSUE TITLE
expandselection/shrinkselection use only one selection

### ISSUE THREAD

**Issue by Felix-The-Ghost** [assaultcube/AC#64]
Those commands introduced in scripts.cfg work with the CubeScript variables selx, sely, selxs, and selys (which are undocumented by the way)

This makes the commands discard any other selections, limiting the commands' usefulness.

I'm not even sure if CubeScript can loop through the selection list currently, but maybe this issue hasn't been noticed yet.

**Comment by ac-stef** [comment]
fixed with a bunch of other stuff in https://github.com/assaultcube/AC/commit/8235300d77f59a2461417122c684fa950003fee0
