### ISSUE TITLE
Crosshairfx 0 does not disable Assault Rifle crosshair effect when shooting 4 or more bullets

### ISSUE THREAD

**Issue by harpsgill** [assaultcube/AC#72]
As it says on the tin. Weirdly, when setting crosshairfx to 0 (default is 1) the Assault Rifle still has a crosshair effect that shows a larger (perhaps 3-5 crosshairsize's larger) crosshair when shooting 4 or more bullets. 

Additionally when in spectate mode, switching to a player using the Assault Rifle will sometimes show this larger crosshair until switching to a new player. 

In sum; crosshairfx 0 should fully disable all crosshair effects.

**Comment by aurhat** [comment]
More options of crosshairfx already added to 'next' branch.
