### ISSUE TITLE
Team Survivor shorthand is TSURV but console command to vote/play is ‘ts’

### ISSUE THREAD

**Issue by harpsgill** [assaultcube/AC#73]
Pretty minor issue. Unlike other modes where the shorthand (as displayed back in Console) and command to vote are the same, Team Survivor uses /ts instead of /tsurv.

**Comment by aurhat** [comment]
Thanks, fixed in commit: https://github.com/assaultcube/AC/commit/5de86f9838205198dc31d8db21c17bcadaa894ed
