### ISSUE TITLE
getmap crash

### ISSUE THREAD

**Issue by RandumKiwi** [assaultcube/AC#78]
Happened in current AC (i.e. not in git, etc). Not sure if this was a one off, or what:

downloading packages/maps/ac_overfreeze.cgz from us.ac-akimbo.net ...
stacktrace:
bin_unix/native_client() [0x4a5faa]
/lib/x86_64-linux-gnu/libc.so.6(+0x36c30) [0x7f30394dfc30]
bin_unix/native_client() [0x4b93d2]
bin_unix/native_client() [0x41213c]
bin_unix/native_client() [0x4124c9]
bin_unix/native_client() [0x4116d3]
bin_unix/native_client() [0x411400]
bin_unix/native_client() [0x423795]
bin_unix/native_client() [0x424a92]
bin_unix/native_client() [0x425159]
bin_unix/native_client() [0x42d67d]
bin_unix/native_client() [0x42cbb4]
bin_unix/native_client() [0x43e226]
bin_unix/native_client() [0x43f492]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f30394caec5]
bin_unix/native_client() [0x407049]
AssaultCube error (11) ()
OpenAL Error (A004): invalid operation, line 367 file openal.cpp
AL lib: ReleaseALC: 1 device not closed

**Comment by ac-stef** [comment]
The rewritten autodownload code ignores paths inside package zips, so the issue no longer applies.
