### ISSUE TITLE
/showspeed doesn't show the correct speed under some conditions

### ISSUE THREAD

**Issue by Cmdr-Thrawn** [assaultcube/AC#89]
Crouching obviously makes you go slower (when walking), but doesn't decrease the number shown by /showspeed

Edit: Also, the same thing happens when going up/down ladders. Your horizontal speed is zero, but is not reflected by the number displayed by /showspeed

**Comment by aurhat** [comment]
It's correct, it shows only straferunning speed: http://en.wikipedia.org/wiki/Strafing_(gaming)#Straferunning . :)
