### ISSUE TITLE
Server crash when playing from same internet IP as server

### ISSUE THREAD

**Issue by lima77** [assaultcube/AC#94]
Hi assaultcubers,
I compiled the server for Raspberry PI and it runs fine except for when I play (with the client on my computer) on this server via the masterserver (internet).
It runs fine in the beginning, but as soon as someone else connects (also after he disconnects) the server will crash on the next map change (new round..) with a segmentation fault.
The problems seems to be that I as client (player) have the same internet IP as the server (the server sits on my desk).
Somewhere in server.cpp I suspect a problem with counting clients when playing from the same internet IP. I am probably not counted as valid player in clients[i] but on map change the server tries to access that player. Or the server is counted as a client itself...... I could not point my finger on it yet...
Greets
lima77

**Comment by ac-stef** [comment]
It is highly unlikely, that the IP address is the problem here.
Is this the only occasion for the server to crash? Does it work with several external players including map changes?
Could you post the log entry from the crash?
Could you compile the server in debug mode and check, if the crash also occurs? (and if it does, also post the log...)
Could you post a build log from compiling the binary for RasPi? Did you make changes to the sources?

**Comment by lima77** [comment]
Thanks for the tips. Good news. I compiled master and "next" branch release and debug. "next" Debug would not compile and the others all crashed.
Then I changed the compiler to g++ and now it works flawlessly, master release.
Logs were not of any help...... "voted for map change....." Segmentation fault.
So clang+ was the problem. It was reported to be a troublemaker on Raspberry Pi occasionally...

**Comment by ac-stef** [comment]
does "next" work with g++? is the log in debug mode more helpful (add "ACDEBUG=yes" to 'make' command)?

**Comment by lima77** [comment]
OK, I tried the follwing
clang+ compile master release: compiled, but crashes on map change with segm. fault
clang+ compile master debug: compiled, but crashes on map change with segm. fault
clang+ compile next release: compiled, but crashes on map change with segm. fault
clang+ compile next debug: does not compile

g++ compile master release: compiled and works!
g++ compile master debug: does not compile and gives the following:

make[1]: Leaving directory '/usr/src/assault/AC/source/enet'
g++ -O0 -g -D_DEBUG -Wall -fsigned-char -ffast-math -rdynamic -DSTANDALONE -I. -Ibot -I../enet/include -c -o crypto-standalone.o crypto.cpp
/tmp/ccNw6Z6z.s: Assembler messages:
/tmp/ccNw6Z6z.s:2995: Error: bad instruction `int $3'
/tmp/ccNw6Z6z.s:3105: Error: bad instruction `int $3'
/tmp/ccNw6Z6z.s:6240: Error: bad instruction `int $3'
/tmp/ccNw6Z6z.s:9816: Error: bad instruction `int $3'
Makefile:150: recipe for target 'crypto-standalone.o' failed
make: *** [crypto-standalone.o] Error 1

I will complete the list, but today and tomorrow I have very limited time...

**Comment by ac-stef** [comment]
Thanks for your efforts.
Yes, the "int 3" breakpoint is asm and most certainly x86-specific. If someone finds an appropriate ARM-equivalent and a good enough platform-identifying define, I'll add it :)
