### ISSUE TITLE
DEMO - display everyone on map

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#96]
Be it on the round map at top-right of screen or on the complete map by pressing `ALT`.

Be it other team players (e.g. in TOSOK) or all other players (e.g. in OSOK), pressing on `ALT` should allow user to see everyone on playing a demo.

**Comment by aurhat** [comment]
Please explain more precisely, what you mean. :)

**Comment by GreenLunar** [comment]
I see only RVSF players when associated with a RVSF player view:
![ac_rapier_ctf_rvsf_Drax](https://cloud.githubusercontent.com/assets/2053884/7292113/63be7ede-e9a1-11e4-88d4-fda79f8fd66d.jpg)

I see only CLA players when associated with a CLA player view:
![ac_rapier_ctf_cla_=FRED=FODE_CU](https://cloud.githubusercontent.com/assets/2053884/7292196/5f2304b6-e9a2-11e4-95c2-1976f375ff4f.jpg)

**Comment by GreenLunar** [comment]
First comment edited:

NEW LINE:
Be it on the round map at top-right of screen or the complete map by pressing `<Tab>`.

ADDED `""` TO `<Tab> `
Be it other team players (e.g. in TOSOK) or all other players (e.g. in OSOK), pressing on `<Tab>` should allow user to see everyone on playing a demo.

**Comment by GreenLunar** [comment]
Oops! I meant to `ALT`, no `<Tab>`

**Comment by aurhat** [comment]
Current behaviour can be uncomfortable, but for some reasons it should stay as it is.

**Comment by GreenLunar** [comment]
What are the reasons?

Why not  change this behaviour when playing a demo?

**Comment by aurhat** [comment]
Security reasons :)

**Comment by GreenLunar** [comment]
In demo?

**Comment by aurhat** [comment]
In open source ;)

**Comment by GreenLunar** [comment]
May you explain how?

**Comment by ac-stef** [comment]
Not in public, no.
