### ISSUE TITLE
Crash on loading map JN1_lab

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#98]
```
$ assaultcube
Using home directory: /home/HOSTNAME/.assaultcube_v1.2
init: sdl
init: net
init: world
init: video: sdl
init: video: mode
init: video: misc
init: gl
Renderer: Gallium 0.4 on AMD RV630 (X.Org)
Driver: 2.1 Mesa 9.1.7
init: console
init: sound
Audio devices: 
Sound: OpenAL Soft / OpenAL Soft (OpenAL Community)
Driver: 1.1 ALSOFT 1.15.1
init: cfg
init: models
init: curl
init: docs
init: localconnect
read map packages/maps/official/ac_desert3.cgz rev 5 (35 milliseconds)
Desert3 by Nieb
loaded textures (128 milliseconds)
loaded mapmodels (229 milliseconds)
loaded mapsounds (605 milliseconds)
game mode is "TDM"
init: mainloop
connecting to GhostBusters |CH|
attempting to connect to 46.28.202.43:28760
connected to server
read map packages/maps/JN1_lab.cgz rev 82 (30 milliseconds)
made by Iguana
couldn't load texture packages/textures/skymaps/humus/meadow_lf.jpg
downloading packages/models/mapmodels/pink/animals/fishanim from 46.28.202.43/~iguana ...
stacktrace:
/usr/share/assaultcube/bin_unix/native_client() [0x80f0d67]
linux-gate.so.1(__kernel_sigreturn+0) [0xffffe400]
/lib/libc.so.6(strcmp+0x19) [0xb713db69]
/usr/share/assaultcube/bin_unix/native_client() [0x8104836]
AssaultCube error (11) (Couldn't open packages/textures/bud/xskull.jpg)
AL lib: (EE) alc_cleanup: 1 device not closed

```

**Comment by GreenLunar** [comment]
Did you reproduce this crash?

**Comment by ac-stef** [comment]
Yes. The zip-files with the animated animal models had "readme" files with no file extension in it. The function to check the extensions did not expect that and crashed. This is fixed.
However - you should be careful about the package servers that you use. Those packages were obviously never tested.

**Comment by GreenLunar** [comment]
Are there AC-standards for AC-packages?
I think, AC should output a warning when a file contain whitespaces (i.e. `%20`) or other unexpected things.
Iguana should, at least, rename these `Read Me` files to `Read_Me`, yet `README` would be the most proper filename, in my opinion, as you would see in many *nix `README` files.


Files in question may be found at http://46.28.202.43/~iguana/packages/models/mapmodels/pink/animals/

```
butterfly1anim/Read Me
butterfly1anim/md3.cfg
butterfly1anim/skin.png
butterfly1anim/tris.md3
```
```
butterfly2anim/Read Me
butterfly2anim/md3.cfg
butterfly2anim/skin.png
butterfly2anim/tris.md3
```
```
fishanim/Read Me
fishanim/md3.cfg
fishanim/skin.png
fishanim/tris.md3
```

**Comment by ac-stef** [comment]
I read your source in the crash report so I knew where to get the packages :)

If you stick to the official package sources, you should only get tested packages. Iguana has much more packages on his server, but apparently not all well tested.

That Readme will be discarded during download anyway. AC only unzips what it needs.

**Comment by GreenLunar** [comment]
> I read your source in the crash report so I knew where to get the packages :)

So I thought.  I have posted it for future reference.
