### ISSUE TITLE
DEMO - SPEC - Do not associate user to any team

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#99]
* I am joining to a server running AssaultCube or playing a demo.
* I am a SPECTATOR GHOST and am not associated with any player's view (a flying ghost).
* *AssaultCube usually associates me with team CLA.*
* Press key `ALT` to see map (same applies to the round map at top-right of screen).
 * When CLA player grabs flag - I can see where RVSF flag is at.
 * When RVSF player grabs flag - I can **not** see where CLA flag is at.
* *When any flag is dropped/lost, everyone can see where it is at.*

Here is an example from a demo in which you can see RVSF player with CLA flag, behind the semi-transparent map.
![ghost_spectator_cla_flag_invisible_256](https://cloud.githubusercontent.com/assets/2053884/7291882/a05dab7e-e99e-11e4-98b8-371f1bc624ee.png)

This is related to issue #96

**Comment by GreenLunar** [comment]
@aurhat, is it fixed?

**Comment by aurhat** [comment]
Not in AssaultCube repository, but only in my fork - you can see it in "Fix and improve showing map and radar icons" commit in experimental branch (maybe not finished). :)

**Comment by aurhat** [comment]
Thanks, fixed. :)
